Open-Agriculture/AgIsoStack-plus-plus

isobus/include/can_address_claim_state_machine.hpp, isobus/include/can_partnered_control_function.hpp, isobus/src/can_address_claim_state_machine.cpp, isobus/src/can_internal_control_function.cpp, isobus/src/can_partnered_control_function.cpp
Fixed internal control functions not getting an address.
Fixed incorrect NAME validation in RX message processing.
Fixed partner control functions never getting populated.
=> [Core]: Fix issues with control function management

isobus/include/can_internal_control_function.hpp, isobus/include/can_network_manager.hpp, isobus/src/can_internal_control_function.cpp, isobus/src/can_network_manager.cpp
Other control function types were getting added to the address table
while doing Rx processing, but ICFs follow a different flow, so I
had to update the address table for them a little differently.
=> [Core]: Fixed internal CFs not added to address table

isobus/include/can_callbacks.hpp, isobus/include/can_network_manager.hpp, isobus/include/can_partnered_control_function.hpp, isobus/src/can_callbacks.cpp, isobus/src/can_network_manager.cpp, isobus/src/can_partnered_control_function.cpp, test/main.cpp
Added parent class context to CAN message callbacks.
This helps the recipient of a callback know what object the callback was destined for.
Fixed network manager timestamp not being updated.
Fix evicting CF address was always evicting without verifying that the address of the claim matched the table
=> [Core]: Add parent pointer to CAN mesage callback data

isobus/include/can_transport_protocol.hpp, isobus/src/can_transport_protocol.cpp
There was a bug in CM TP Tx sessions where if the packet was broken up into multple CTS/RTS chunks, the stack would send repeated data and abort. These issues should now be resolved.
=> [TP]: Fix issues with CM TP Tx session spanning multiple CTS/RTS cycles

.gitignore, README.md, isobus/CMakeLists.txt, isobus/include/can_constants.hpp, isobus/include/can_general_parameter_group_numbers.hpp, isobus/include/isobus_virtual_terminal_client.hpp, isobus/src/isobus_virtual_terminal_client.cpp, utility/CMakeLists.txt, utility/include/processing_flags.hpp, utility/include/system_timing.hpp, utility/src/processing_flags.cpp, utility/src/system_timing.cpp
This is the first major ISO11783 feature for this project!
Currently only object pools that are able to be uploaded by transport protocol (<= 1785 bytes) or pools that can be split up into 1785 byte size chunks are supported. ETP support is coming next.
I have tried to include functions all the way up to VT version 6 where it was easily doable, and support event based callbacks from VT events, like button presses or soft key presses. But providing the object pools themselves is up to whomever is using the client class. I would be happy to make an example for this and add it to the repo if someone has some non-copyrighted or MIT licensed object pools that I could commit to the repo.
If you or someone you know is interested in helping me test this VT functionality, please reach out. I am in …
=> [VT]: Add Virtual Terminal Client

isobus/include/can_transport_protocol.hpp, isobus/src/can_transport_protocol.cpp
- CTS message and state were unimplemented
- EOM acknowledgement was being sent too early due to it not taking into account the sequence number overhead in the payload frames.
- Normalized whitespace in the affected files
=> Fixed receiving TP connection mode messages

README.md, isobus/src/can_transport_protocol.cpp, socket_can/src/socket_can_interface.cpp
There was an issue when transmitting out of the CAN message transmit queue where we would only pull the first item out of the queue every iteration.
This was causing us to under-utilize the bus, and take longer to send TP messages than needed.
Fixed an off-by-one error when comparing the maximum protocol payload for TP to the transmit size.
Changed TP CM Tx to complete, as I have now tested all message lengths from 9 to 1785 bytes, and all appeared to succeed.
=> Fix transmit queue processing too slow, fix sending exactly 1785 bytes

isobus/src/can_extended_transport_protocol.cpp
ETP protocol was accepting messages destined for the global address, which is not valid according to the ISO-11783 specification.
Furthermore, it was mishandling the message when it was accepted when the destination control function was `nullptr`, which caused a crash.
This PR fixes that behavior so the protocol does not accept messages destined for global.
=> [ETP]: Fix ETP accepting globally destined messages

isobus/src/can_identifier.cpp
Fixed an issue where broadcast PGNs would be truncated when constructing a CAN ID out of its components.
This was affecting BAM transmits to have the wrong PGN embedded in the payload.
=> [Core]: Fixed a truncation when constructing some CAN IDs

isobus/include/can_network_configuration.hpp, isobus/include/can_transport_protocol.hpp, isobus/src/can_network_configuration.cpp, isobus/src/can_transport_protocol.cpp
Closes #21
Solves several issues with transmitting BAM sessions and adds configurable BAM frame delay according to ISO 11783-3. 
With this PR I believe I have validated that basic BAM transmitting is working.
More extensive testing will follow for all BAM message lengths and timing values before I will officially update the state as shown in the README.
=> TP: BAM Tx improvements

isobus/src/can_extended_transport_protocol.cpp
Fixed an issue where ETP's send function would always return `false`, when trying to transmit, even though a session was created.
=> ETP: Fix ETP protocol send function return value

CMakeLists.txt, examples/transport_layer/CMakeLists.txt, examples/transport_layer/README.md, examples/transport_layer/main.cpp
This PR adds a program to the examples folder that demonstrates how to set up the CAN stack in a basic sense, and how to transmit CAN messages of any length to any partner or the global address.
=> Added Transport Layer Example Program

CMakeLists.txt, README.md, examples/diagnostic_protocol/CMakeLists.txt, examples/diagnostic_protocol/main.cpp, isobus/CMakeLists.txt, isobus/include/can_general_parameter_group_numbers.hpp, isobus/include/can_network_manager.hpp, isobus/include/isobus_diagnostic_protocol.hpp, isobus/src/isobus_diagnostic_protocol.cpp
Added the following ISO 11783 and J1939 diagnostic protocol components:
* Diagnostic Message 1 (DM1) - Active diagnostic trouble codes, supports either J1939 mode or ISO 11783 mode (default)!
* Diagnostic Message 2 (DM2) - Previously active diagnostic trouble codes
* Diagnostic Message 3 (DM3), -  Reset of previously active diagnostic trouble codes
* Diagnostic Message 11 (DM11) - Reset for active diagnostic trouble codes
* Diagnostic Message 22 (DM22) - Individual clear/reset of active and previously active diagnostic trouble code
* ISO 11783 Product Identification message
* ISO 11783 Diagnostic protocol "supported protocols" message (SAE J1939-73 support is advertised by the stack)
Added a diagnostic protocol example program to show how to use it (if you want to use it).
Updated README
=> ISO 11783 / J1939 Diagnostic protocol

README.md, examples/diagnostic_protocol/main.cpp, isobus/include/can_general_parameter_group_numbers.hpp, isobus/include/isobus_diagnostic_protocol.hpp, isobus/src/isobus_diagnostic_protocol.cpp
Now you can tell the stack ECU and software ID information, and it will respond with that information when it is requested. These messages are extrememly common, and are used by a lot of onboard and offboard (OBD) tools to interrogate a system.
=> [DP]: Added Software ID and ECU ID

isobus/include/isobus_diagnostic_protocol.hpp
Compilation was failing during testing with GCC 11 on RHEL 9 due to a missing include for string.
Added that string, now there are no errors or warnings on GCC 11.2.1
=> [DP]: Fix diagnostic protocol compilation fails on GCC 11.2.1

socket_can/src/socket_can_interface.cpp
When exiting, we now clean up the socket CAN layer better so that we delete any allocated frame handlers and stop relying on a user to do it. Previously this would leak about 232 bytes per CAN channel right at exit time.
=> [Core]: Fix a small memory leak in the socket CAN layer

CMakeLists.txt, README.md, examples/pgn_requests/CMakeLists.txt, examples/pgn_requests/README.md, examples/pgn_requests/main.cpp, isobus/CMakeLists.txt, isobus/include/can_callbacks.hpp, isobus/include/can_general_parameter_group_numbers.hpp, isobus/include/can_network_manager.hpp, isobus/include/can_parameter_group_number_request_protocol.hpp, isobus/include/isobus_diagnostic_protocol.hpp, isobus/src/can_parameter_group_number_request_protocol.cpp, isobus/src/isobus_diagnostic_protocol.cpp
* Added a new protocol to handle PGN requests and requests for repetition rate. This should make dealing with PGN requests easier, as the stack can handle request encoding, ACKs and NACKs. This will also make it easier to comply with the ISO 11783 rule "A NACK is required if the PGN is not supported" for PGN requests, as the stack can now do this for you.
* Converted the diagnostic protocol to use the new PGN request protocol instead of registering for all PGN requests
* Added a new example program that shows how to deal with PGN requests
* Fixed a memory double free issue in diagnostic protocol where a protocol instance could be doubly deleted
* Updated the README with current status
* Added `doxyfile` to the doxygen command in the README to be sure that it pulls the file in rather than …
=> [PR]: Add PGN Request Protocol

socket_can/src/socket_can_interface.cpp
For issue #44
`sys/time.h` include was missing. It seems to be brought in by `chrono` (I think) on RHEL and Ubuntu but not on Alpine.
With this fix the library appears to compile fine on Alpine:latest.
=> [Core]: Fix compilation on Alpine Linux

README.md, sphinx/source/Installation.rst
Tutorial stated to use `git clone` instead of `git submodule add`. Also changed to use https for the submodule add step instead of ssh just in case the user does not have ssh set up and reflected this change in README as well.
=> [Meta]: Fix submodule instructions in tutorial

CMakeLists.txt, README.md, doxyfile, examples/diagnostic_protocol/CMakeLists.txt, examples/diagnostic_protocol/main.cpp, examples/pgn_requests/CMakeLists.txt, examples/pgn_requests/main.cpp, examples/transport_layer/CMakeLists.txt, examples/transport_layer/main.cpp, examples/vt_version_3_object_pool/CMakeLists.txt, examples/vt_version_3_object_pool/main.cpp, hardware_integration/CMakeLists.txt, hardware_integration/README.md, hardware_integration/include/can_hardware_interface.hpp, hardware_integration/include/can_hardware_plugin.hpp, hardware_integration/include/socket_can_interface.hpp, hardware_integration/src/can_hardware_interface.cpp, hardware_integration/src/socket_can_interface.cpp, sphinx/source/FAQ.rst, sphinx/source/Installation.rst, sphinx/source/Tutorials/Adding a Destination.rst, sphinx/source/Tutorials/Receiving Messages.rst, sphinx/source/Tutorials/The ISOBUS Hello World.rst, test/address_claim_test.cpp
* Broke-up the socket-can layer to be a more generic abstraction layer.
- Now, if you want to implement your own driver for some other CAN interface, you just need to inherit from `CANHardwarePlugin` and write the 5 functions needed. Then, pass that class to `CANHardwareInterface` instead of the device name like before. See the examples or tutorial for how to do this.
* Added a way to not build the examples! Just define NO_EXAMPLES when configuring via CMake `-DNO_EXAMPLES`
* Added a CMake way to allow selecting other CAN drivers that aren't socket CAN (right now that's still the only option)
Renamed the `SocketCANInterface` library to `HardwareIntegration`. _You may need to update your CMake!_
=> [Core]: Refactor CAN Hardware Abstraction

hardware_integration/src/can_hardware_interface.cpp
This was causing a Linux dependency even when not using socket CAN
=> [Core]: Fix unneeded includes in CAN Hardware Interface

isobus/src/can_extended_transport_protocol.cpp, isobus/src/can_network_manager.cpp, isobus/src/can_parameter_group_number_request_protocol.cpp, isobus/src/can_transport_protocol.cpp, isobus/src/isobus_virtual_terminal_client.cpp, utility/CMakeLists.txt, utility/include/to_string.hpp
Changes logging calls that used `std::to_string` to use a workaround implementation.
This is to support tool-chains that do not implement `std::to_string`.
Closes #52 
Compiles with the esp32 compiler using Arduino IDE now:
```
Sketch uses 463952 bytes (35%) of program storage space. Maximum is 1310720 bytes.
Global variables use 23252 bytes (7%) of dynamic memory, leaving 304428 bytes for local variables. Maximum is 327680 bytes.
```
=> [Core]: Change all std::to_string calls to use a workaround

CMakeLists.txt, README.md, examples/diagnostic_protocol/CMakeLists.txt, examples/pgn_requests/CMakeLists.txt, examples/transport_layer/CMakeLists.txt, examples/vt_version_3_object_pool/CMakeLists.txt, hardware_integration/CMakeLists.txt, isobus/CMakeLists.txt, utility/CMakeLists.txt
- Add CMake ALIAS targets for all current libraries
- Consume the new alias targets in all calls to target_link_libraries
- Update gtest to be found using either find_package or the fetchcontent method
- Add missing alias to gtest for pre cmake 3.20 support to be unified
- Solves #42
Signed-off-by: Ryan Friedman <ryan_friedman@trimble.com>
=> [42] CMake Alias Targets

CMakeLists.txt, README.md, examples/diagnostic_protocol/CMakeLists.txt, isobus/include/isobus/isobus/can_general_parameter_group_numbers.hpp, isobus/include/isobus/isobus/isobus_diagnostic_protocol.hpp, isobus/src/isobus_diagnostic_protocol.cpp, test/dm_13_tests.cpp
*Added J1939 DM13
DM13 stops and starts broadcast messages for a specific channel, reducing the bus load under some conditions.
As part of the Diagnostic Protocol, it will automatically stop the DM1 message if the DM13 for your network is received.
You can use this protocol's broadcast state in your application to further reduce your bus load if you desire.
You can also suspend your own broadcasts by sending the DM13 to the network if you want.
=> [DP] Add support for J1939 Diagnostic Message 13

README.md, examples/diagnostic_protocol/CMakeLists.txt, examples/pgn_requests/CMakeLists.txt, examples/transport_layer/CMakeLists.txt, examples/vt_version_3_object_pool/CMakeLists.txt, sphinx/source/FAQ.rst, sphinx/source/Installation.rst, sphinx/source/Tutorials/The ISOBUS Hello World.rst
Also added `PRIVATE` to all example `target_link_libraries` calls
Basically here's what's happening... in all the examples when using static libraries the `TransportProtocolManager` and `ExtendedTransportProtocolManager` were not getting linked in from the library into the executable. This is because linkers do not need to do that if they think that translation unit is not referenced anywhere in the final executable. This was causing all transport layer functions to fail, as the transport layer relies on those static objects being instantiated. Using shared libraries fixes this, but because static is the default now, I've added some logic to CMake to force the whole isobus::Isobus archive to be linked.
@RFRIEDM-Trimble I would be interested in your opinion on this if you have one, as it …
=> [#61]: Help prevent TP and ETP from being optimized out when using static libs

examples/diagnostic_protocol/main.cpp, examples/pgn_requests/main.cpp, examples/transport_layer/main.cpp, examples/vt_version_3_object_pool/main.cpp, sphinx/source/Tutorials/Adding a Destination.rst, sphinx/source/Tutorials/Receiving Messages.rst, sphinx/source/Tutorials/The ISOBUS Hello World.rst, sphinx/source/Tutorials/Virtual Terminal Basics.rst
Now the examples and tutorials will warn you if the underlying CAN interface is down.
Closes #66
=> [#66] Add CAN interface down warnings

isobus/src/can_extended_transport_protocol.cpp, isobus/src/isobus_virtual_terminal_client.cpp
Fix for object pools upload failing for pool sizes ending in 8 bytes in the last message:
Example pool log uploaded successful
```
[ETP]: numberBytesLeft=35
[ETP]: numberBytesLeft=28
[ETP]: numberBytesLeft=21
[ETP]: numberBytesLeft=14
[ETP]: numberBytesLeft=7
[ETP]: Session Closed
```
Whereas custom pool failed:
```
[ETP]: numberBytesLeft=29
[ETP]: numberBytesLeft=22
[ETP]: numberBytesLeft=15
[ETP]: numberBytesLeft=8
[ETP]: Aborting session, unable to transfer chunk of data
[ETP]: Session Closed
```
PR also includes some small refactoring of some duplicated code I noticed in ETP process_message
=> [VT] Fix for uncommon object pool upload failure

.deepsource.toml, hardware_integration/src/can_hardware_interface.cpp, hardware_integration/src/socket_can_interface.cpp
SocketCAN interface now closes correctly when interface is down. It also logs a warning for this to CANStackLogger. And resolved an issue where the hardware interface keeps reopening the CANHardwarePlugin.
=> [Core]: Fix SocketCAN interface unwanted behaviour

isobus/src/can_extended_transport_protocol.cpp, isobus/src/isobus_virtual_terminal_client.cpp
* Now the VT state machine will restart the connection process for disconnects and timeouts that were previously not handled.
* Now we will properly handle a VT server that NACKs our ECU to VT messages by reconnecting. This is somewhat likely to happen while debugging, since status messages stop while you are at a breakpoint, and when we resume the state machine is out of sync with the server, so it may NACK us.
* Added cleanup of VT PGN callback registrations.
* Some VT logging improvements
* Fixed a couple bugs in ETP, where Tx complete callback might not get called for some timeouts.
Closes #64
=> [VT]: Disconnection Handling Improvements

isobus/src/can_extended_transport_protocol.cpp
Fixing an issue with ETP similar to what we fixed in TP in #78 where it's not filtering out messages not destined for an internal control function.
=> [ETP]: Don't process messages that aren't destined for an ICF

isobus/src/can_network_manager.cpp, isobus/src/isobus_diagnostic_protocol.cpp, isobus/src/isobus_virtual_terminal_client.cpp
Just some small cleanup items:
* Fixed a C style cast
* Reduced the scope of a vector in DM1 and DM2 transmits
* Fixed a situation where we might use an uninitialized variable in VT pool upload
=> Misc. Style Fixes

isobus/src/can_transport_protocol.cpp
Fixed an issue where the data parsed out of TP.CM sessions would be incorrect slightly because the decoding loop for the TP data mux was using 8 bytes of payload instead of 7.
=> [TP]: Fix a nasty off-by-one error when decoding TP.CM packets

examples/vt_version_3_object_pool/main.cpp, isobus/include/isobus/isobus/isobus_virtual_terminal_client.hpp, isobus/src/isobus_virtual_terminal_client.cpp, utility/include/isobus/utility/iop_file_interface.hpp, utility/src/iop_file_interface.cpp
* Now, if you specify a version label when setting your object pool to the VT client, it will try and store that pool on the VT server so that it can be easily re-activated later without the need to re-transmit the entire thing.
* Added a utility function for generating a somewhat random hash of an object pool to assist in making unique version labels. Use of this is totally optional, and you can label them however you want.
* Note, all object pools for your working set must share a label (this is part of the standard) so only the first object pool is looked at for a version label right now.
* I have plans to automatically delete out-of-date labels in the next VT feature PR.
* Updated VT example program to use a label
Closes #67
=> [VT} Automatic object pool version load/store

isobus/src/can_network_manager.cpp
This was causing duplicate entries in the active table and would cause get_full_name to return 0 for partners. Also short circut the check to find matching control functions in the active table when one is located.
Closes #94
=> [Core]: Fix not assigning full NAME to partners when placing them in the active table

isobus/src/isobus_virtual_terminal_client.cpp
This may or may not have caused a crash or assert
=> [VT]: Fix an out of bounds write when storing object pool version

README.md, examples/diagnostic_protocol/CMakeLists.txt, examples/nmea2000/CMakeLists.txt, examples/pgn_requests/CMakeLists.txt, examples/transport_layer/CMakeLists.txt, examples/vt_version_3_object_pool/CMakeLists.txt, isobus/include/isobus/isobus/can_extended_transport_protocol.hpp, isobus/include/isobus/isobus/can_network_manager.hpp, isobus/include/isobus/isobus/can_protocol.hpp, isobus/include/isobus/isobus/can_transport_protocol.hpp, isobus/src/can_extended_transport_protocol.cpp, isobus/src/can_network_manager.cpp, isobus/src/can_protocol.cpp, isobus/src/can_transport_protocol.cpp, sphinx/source/FAQ.rst, sphinx/source/Installation.rst, sphinx/source/Tutorials/The ISOBUS Hello World.rst
Dealing with the "whole-archive" behavior between compilers was very annoying, so I made the affected objects non-static members of the network manager. Now they will not be removed by your linker erroneously. Updated readme and tutorial docs to match this change.
=> [Core]: Changed protocol list to be non-static to remove the need for "whole-archive"

CMakeLists.txt, isobus/src/can_internal_control_function.cpp, isobus/src/can_network_manager.cpp, isobus/src/can_partnered_control_function.cpp, test/core_network_management_tests.cpp
When a partner or ICF is deleted, now we will null out its pointer in the list rather than erasing it, which could have caused an exception if the deleted object was a created via smart pointer. Likewise, when a new object is created, we will search first for empty spots in the list before allocating new ones to keep the list as small as possible. Added a trivial unit test to detect exceptions on creation and deletion of ICFs and Partners.
Closes #102
=> [#102]: Change how partner and ICF list maintenance is done when members are deleted

isobus/include/isobus/isobus/can_internal_control_function.hpp, isobus/include/isobus/isobus/can_network_manager.hpp, isobus/src/can_internal_control_function.cpp
Changed to avoid a possible segfault while searching a list for nullptr in a static constructor of an ICF.
This was crashing my super secret VT server project on this line:
`auto location = std::find(internalControlFunctionList.begin(), internalControlFunctionList.end(), nullptr);`
=> [Core]: Change internal control function list to be a vector

isobus/include/isobus/isobus/can_network_manager.hpp, isobus/src/can_network_manager.cpp
This is is essentially a way to register for PGN callbacks from anybody. This should really only be used when the other registration method doesn't work for your use case, but for some server applications (VT and File Server come to mind) it seems like it would be beneficial to have a way to get all messages with a specific PGN without registering specific partners.
=> [Core]: Added a way to register for a PGN callback for any CF

sphinx/source/Tutorials/Adding a Destination.rst, sphinx/source/Tutorials/Receiving Messages.rst, sphinx/source/Tutorials/The ISOBUS Hello World.rst, sphinx/source/Tutorials/Virtual Terminal Basics.rst
Updated tutorial docs to fix out of date include paths. Also added clarification about object names in VT tutorial.
Closes #108
=> [#108]: Update sphinx tutorial docs

README.md, hardware_integration/CMakeLists.txt
* Added a short section to the readme file about installing the library
* Added mentions to the main README for how to set the CAN driver plugin
* Added a trivial check to not choose socket CAN by default on Windows and instead choose the PEAK driver
=> Update README with install and CAN driver instructions

isobus/src/isobus_virtual_terminal_client.cpp
* Fixed two VT member variables not getting initialized at construction time. 
* Fixed an unintentional data copy.
=> [VT]: Minor VT code quality fixes

isobus/src/isobus_virtual_terminal_client.cpp
Instead of checking for the connected state we should always parse VT NACKs and restart communication.
Closes #114
=> [#114]: Always process VT NACKs

isobus/include/isobus/isobus/can_extended_transport_protocol.hpp, isobus/include/isobus/isobus/can_transport_protocol.hpp, isobus/include/isobus/isobus/nmea2000_fast_packet_protocol.hpp, isobus/src/can_extended_transport_protocol.cpp, isobus/src/can_transport_protocol.cpp, isobus/src/nmea2000_fast_packet_protocol.cpp
Moved `process_session_complete_callback` function call to `close_session` to make sure it always gets called when session closes. `process_session_complete_callback` itself checks whether or not a callback is given, which is right now only for transmitting sessions. Though the name "session complete callback" itself doesn't constrain it to transmitting sessions only and so this change also allows receiving sessions to use the callback system if needed.
**Related bug:**
After receiving an abort for a transmitting etp session for an object pool, the callback didn't get called and therefore the VT client never got to reset.
```console
I (366) Main: Starting setup...
I (636) Main: Loaded object pool from vtpooldata.iop
I (636) Main: Setup complete!
I (676) Logger: [NM]: A Partner Has Claimed …
```
=> [ETP/TP/FP]: Fix session complete callback not called sometimes.

sphinx/source/FAQ.rst, sphinx/source/Installation.rst, sphinx/source/Tutorials/The ISOBUS Hello World.rst, sphinx/source/Tutorials/Virtual Terminal Basics.rst
* Replaced ${CMAKE_THREAD_LIBS_INIT} with Threads::Threads (See #54)
* Added CMake instructions to VT tutorial
* Fixed `RegisterVTButtonEventCallback` and `RegisterVTSoftKeyEventCallback` should be snake_case
* Clarified use and instructions around `objectPoolObjects.h` and `VT3TestPool.iop`
* Added a section about the other callbacks, like string value events
* Added some more references to the API docs
Closes #112 
Closes #54
=> [#112]: Update VT tutorial with CMake, Fix omissions and a couple outdated function names

isobus/src/isobus_virtual_terminal_client.cpp
This change will delete stale object pools that the VT has saved to NVM for your ISO NAME. This is mostly a courtesy to other people so you're not hogging space on the VT for an object pool that you're not using actively.
=> [VT]: Automatically clean up old versions of object pools

isobus/src/can_network_manager.cpp
This takes the need off the consumer to check that the destination was an internal control function or a broadcast.
=> [Core]: Improve destination validation in "any control function" callbacks

isobus/src/can_extended_transport_protocol.cpp
* Fixed an off by 1 error in parsing the protocol bytes out of each ETP frame
* Fixed the data offset into the resulting message buffer would roll over due to it using the wrong counter
* Fixed an erroneous log message by setting the expected ETP packet count properly when we CTS less than 255 frames, usually at the end of a session.
Closes #121
=> [ETP]: Fix ETP Rx message contents not matching the expected content

isobus/src/can_extended_transport_protocol.cpp, isobus/src/can_transport_protocol.cpp
Transport session completion wasn't calling the any control function callbacks, which could cause missed messages.
=> [ETP/TP]: Have transport layers call the any cf callback processor on session completion

isobus/include/isobus/isobus/can_extended_transport_protocol.hpp, isobus/src/can_extended_transport_protocol.cpp
This has as result that ETP will reject the send message if it can be processed by the TP instead.
Closes #128
=> [ETP] Add minimum data length requirement

isobus/include/isobus/isobus/can_control_function.hpp, isobus/include/isobus/isobus/can_network_manager.hpp, isobus/include/isobus/isobus/can_partnered_control_function.hpp, isobus/src/can_control_function.cpp, isobus/src/can_internal_control_function.cpp, isobus/src/can_network_manager.cpp, isobus/src/can_partnered_control_function.cpp
Added lots of improvements to control function list/table maintenance.
* Fix issues with mapping a `PartneredControlFunction` with an `ExternalControlFunction` when the partner was created after the stack already had an `ExternalControlFunction` object matching that ECU. In other words, if you made a partner after address claiming was complete, the stack would not resolve that partner to the right ECU. Now it should work no matter when you create a partner.
* Fixed some missing checks for can channel ID.
* Fixed not cleaning up our internal tables if a partner was deleted. Now you can delete partners that were created dynamically and we will automatically either prune it from the appropriate lists or replace the `PartneredControlFunction` with a `ExternalControlFunction`.
* Added a mutex …
=> Control function maintenance improvements

isobus/include/isobus/isobus/can_message.hpp, isobus/src/can_message.cpp, isobus/src/isobus_virtual_terminal_client.cpp
Allows reading of the following types directly from `CANMessage` object using dedicated functions:
- uint8_t 
- uint16_t
- uint32_t
- uint64_t
- bool
Also adjusted the `process_rx_message` in `VirtualTerminalClient` to use these functions already.
Closes #137
=> [Core]: Add basic named reading of byte buffer

isobus/src/isobus_virtual_terminal_client.cpp
Instead of reading object as u64 it should've been u16. Not sure how I missed this 🤷🏽‍♂️
=> [VT]: Fix misreading aux assignment object ids

isobus/include/isobus/isobus/can_message.hpp, isobus/src/can_message.cpp, isobus/src/isobus_virtual_terminal_client.cpp
When we were getting NACKs it was causing a crash due to accessing index 8 after converting to the named read functions.
=> [VT]: Fix accessing a u24 as a u32 when parsing VT NACK

.github/workflows/cmake.yml
Previously just the library was built, but it's good to make sure the examples build.
=> [Meta]: Change CI build to compile the example programs

CMakeLists.txt, examples/diagnostic_protocol/CMakeLists.txt, examples/nmea2000/CMakeLists.txt, examples/pgn_requests/CMakeLists.txt, examples/transport_layer/CMakeLists.txt, examples/vt_aux_n/CMakeLists.txt, examples/vt_version_3_object_pool/CMakeLists.txt, hardware_integration/CMakeLists.txt, isobus/CMakeLists.txt, sphinx/source/Tutorials/Virtual Terminal Basics.rst, utility/CMakeLists.txt
This breaks all current applications importing the current "isobus::SystemTiming". Their fix would be to change it to "isobus::Utility".
I feel like this change would otherwise be due sooner or later, since the current library "SystemTiming" already includes more than only the system timing, but change the naming leads to breaking applications so I think we should do this before any release.
I'm also open for other name suggestions like "SystemUtility", etc
=> [Meta]: Rename library SystemTiming to Utility

.github/workflows/cmake.yml, .github/workflows/linting.yml, README.md
- Updated clang-format linting action:
- The `socket_can` matrix path is not yet there anymore and resulted into running clang-format in the whole repo instead. But this only took around 50 seconds so it's also acceptable to just run one clang-format linting action for the whole repo as it won't take too long and we wouldn't have the same problem again in the future.
- Also removed some other properties as they were either default one or optional and wouldn't get used.
- Bumped the action from 4.9.0 to 4.10.1
- Added `-DBUILD_TESTING=ON` to the cmake build action so the `ctest` job can actually run testing. (Also my vscode wanted to do some formatting on the `cmake.yml` file which I guess is fine as it looks more inline with the other action files now.)
=> [Meta]: Small QOL updates to Github actions files

.github/workflows/sonar.yml
This PR adds the parts of the GitHub action necessary for SonarCloud to generate coverage analyses.
Reference used: https://github.com/sonarsource-cfamily-examples/linux-cmake-gcovr-gh-actions-sc/blob/main/.github/workflows/build.yml
=> [Meta]: Add coverage analyses action of SonarCloud

CMakeLists.txt, sonar-project.properties
I missed this parameter in #155 I'm afraid. There were no coverage results in [this action](https://github.com/ad3154/ISO11783-CAN-Stack/runs/10912856878). And I guess we won't find out if this fixes the missing coverage results either without merging it... Or is there any other way I'm missing here?
=> [Meta]: Add missing tests directory parameter

hardware_integration/src/can_hardware_interface.cpp, isobus/include/isobus/isobus/can_network_manager.hpp, isobus/src/can_network_manager.cpp, isobus/src/can_transport_protocol.cpp
* Fixed issue in TP similar to the one I fixed in #141 
* Fixed a check where the scanner was worried about class slicing (but no slicing was probably happening?) 
* Add a condition to the can thread's wait. We really just want it to always wake up, as there are tons of things that trigger that thread but guidelines say we should have some condition.
Putting this in as a draft initially to see if I can throw in a few more improvements and to verify that it actually passes the sonar check
=> [Core]: Fix the sonar blocker items

CMakeLists.txt, hardware_integration/CMakeLists.txt, hardware_integration/include/isobus/hardware_integration/virtual_can_plugin.hpp, hardware_integration/src/virtual_can_plugin.cpp, test/virtual_can_plugin_tests.cpp
- Added VirtualCANPlugin to communicate with ourself in testing environments.
- Some basic unit tests for the VirtualCANPlugin.
- Modified building of GTest such that it will still compile the tests that don't rely on SocketCAN when SocketCAN is not available.
- Moved setting of `--coverage` flag to CXX compiler up so SonerCloud will hopefully now track the other files for code coverage as well.
TLDR: I just wrote my first C++ unit test 😄
=> [Core]: Add virtual CAN driver plugin with unit tests

isobus/src/can_network_manager.cpp
Now the stack will properly fail to send the message and log a helpful message rather than sending a PGN of all zeros. 
Also removed an ancient todo that made no sense.
Closes #158
=> [#158]: Improve handling of broadcast PGNs sent to a non-broadcast destination

examples/diagnostic_protocol/CMakeLists.txt, examples/nmea2000/CMakeLists.txt, examples/pgn_requests/CMakeLists.txt, examples/transport_layer/CMakeLists.txt, examples/vt_aux_n/CMakeLists.txt, examples/vt_version_3_object_pool/CMakeLists.txt, hardware_integration/CMakeLists.txt, hardware_integration/src/can_hardware_interface.cpp, isobus/CMakeLists.txt, isobus/include/isobus/isobus/can_partnered_control_function.hpp, isobus/src/can_network_manager.cpp, isobus/src/can_partnered_control_function.cpp, utility/CMakeLists.txt
- Don't always wake up hardware interface thread as it raises watchdog timer exceptions on some platforms (e.g. ESP32). I know sonar doesn't like it, but I guess it gets enough inputs for it to wake up such that is safe to ignore the warning.
- Switch from copying `ParameterGroupNumberCallbackData` to returning a pointer to optimize memory performance.
=> [Core]: Optimize get pgn callback by returning ptr

.github/workflows/build.yml
This was the case when the workflow trigger event ran when a commit was pushed to main branch. See [runs/4136493254](https://github.com/ad3154/ISO11783-CAN-Stack/actions/runs/4136493254)
=> [Meta]: Run build workflow when approve job is skipped

.github/workflows/build.yml
- Moved checkout step to the top of the job
- Add always condition to if statement of build workflow
It should now finally run successful, I tested it here:
https://github.com/GwnDaan/ISO11783-CAN-Stack/actions/runs/4146377330/jobs/7171955224
**Note:** the build workflow will fail on this PR as the checkout step is not at the top of the job for the base commit of this PR. We can't do anything about it because of the nature of the `pull_request_target` trigger.
=> [Meta]: Fix build workflow not running on main branch commit

isobus/include/isobus/isobus/isobus_virtual_terminal_client.hpp, isobus/src/isobus_virtual_terminal_client.cpp
Changed all instances of "color" to "colour" to match ISO 11783
=> [#170] Standardize "color" to "colour"

examples/diagnostic_protocol/main.cpp, examples/nmea2000/main.cpp, examples/pgn_requests/main.cpp, examples/transport_layer/main.cpp, examples/vt_aux_n/main.cpp, examples/vt_version_3_object_pool/main.cpp
Pushed this to fix the following issue when building examples under linux:
```
../../../examples/nmea2000/main.cpp:41:2: error: ‘_exit’ was not declared in this scope; did you mean ‘_Exit’?
41 |  _exit(EXIT_FAILURE);
|  ^~~~~
|  _Exit
```
=> [Examples]: Change `_exit` to `_Exit`

CMakeLists.txt, isobus/src/isobus_diagnostic_protocol.cpp, test/diagnostic_protocol_tests.cpp
* Fixed an issue where duplicate instances of the diagnostic protocol would be created when only 1 should exist. 
* Fixed an issue when deleting a diagnostic protocol, where we might throw an exception when traversing the list of protocols due to us deleting objects from within that list while traversing it. 
* Renamed the DM13 test to be more inclusive of all diagnostic protocol tests. 
* Added a test for creating and destroying diagnostic protocols.
=> [DP]: Fix diagnostic protocol create/destroy bugs

.github/workflows/build.yml
SonarCloud should now be able to know which PR an analysis is run on. With that it should comment on the PR with the results of the analysis.
I think these changes are necessary as I found the following in the logs:
From an old `sonar.yml` action ([source](https://github.com/ad3154/ISO11783-CAN-Stack/actions/runs/4120407728/jobs/7115102457)):
```
INFO: Github event: pull_request
INFO: Auto-configuring pull request 169
```
Where it's now just ([source](https://github.com/ad3154/ISO11783-CAN-Stack/actions/runs/4149001579/jobs/7177575436)):
```
INFO: Github event: pull_request_target
```
where it's not telling us it's auto configuring, so I guess we can configure it manually for now😄 
Let's pray this does the job, I find the use of the `pull_request_target` event still kind of sketchy haha
=> [CI] Make sonar-scanner aware of pull request key, branch, base and repo

.github/workflows/build.yml, isobus/src/can_internal_control_function.cpp, isobus/src/can_partnered_control_function.cpp
Sometimes the order of static object destruction can be a bit unpredictable, so sometimes I was seeing that the lists that contain the internal and partner control functions would be cleared before we could access them in the destructors of those objects specifically when those objects were global statics (like in the examples). So I added a trivial check to ensure those lists contains > 0 objects before trying to do any further operations with it inside those destructors.
=> [Core]: Mitigate an order of operations issue with static destructors

isobus/include/isobus/isobus/can_NAME.hpp
This started with us missing "Task Controller = 130" and spiraled into me just adding all missing function codes. The common ones cover most things, but the rarer ones are explicitly called out. Some of the ISO descriptions are non-existent, especially for the "Marine" industry group, but I added the descriptions that I could.
=> [Core]: Added remaining ISO Function Codes

CMakeLists.txt, hardware_integration/include/isobus/hardware_integration/can_hardware_interface.hpp, hardware_integration/include/isobus/hardware_integration/virtual_can_plugin.hpp, hardware_integration/src/can_hardware_interface.cpp, hardware_integration/src/virtual_can_plugin.cpp, test/hardware_interface_tests.cpp
This PR is mostly refactoring the CANHardwareInterface class and adding some basic tests to it. I planned to change it up more, but before doing that I think it's useful to get thoughts of others on this changed version. 
The changes I made:
- Replace raw pointers with smart pointers.
- Reduce number of raw locks with gaurded and unique locks.
- Switch canLibNeedsUpdate from bool with mutex, to atomic_bool
- Improved consistency in naming, e.g. camelCase for variables and snake_case for functions
It's been some time since I made these changes and I notice now that I went away from the single-return path for some smaller functions (mostly to use early-returns instead). I know not everyone likes it, but I see a few benefits for it:
- Have the logging message close to the if condition that …
=> [Core]: Improvements to CANHardwareInterface 

.github/workflows/build.yml, sonar-project.properties
SonarCloud stopped producing useable analysis for the main branch, which is kind of obvious as it treated every workflow event as an PR... With this PR it should be able to run the analysis on the main branch again 😄
=> [CI]: Make sonar-scanner run on regular push to main

CONTRIBUTING.md
Adds a requirement to the `CONTRIBUTING.md` file regarding the test coverage. Also tried to increase the welcomingness of the first few sentences of the file. Inspiration: https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines
Closes #154
=> [Meta]: Welcome contributions and add code coverage requirement

examples/diagnostic_protocol/main.cpp, examples/nmea2000/main.cpp, examples/pgn_requests/main.cpp, examples/transport_layer/main.cpp, examples/vt_aux_n/main.cpp, examples/vt_version_3_object_pool/main.cpp, hardware_integration/include/isobus/hardware_integration/can_hardware_interface.hpp, hardware_integration/src/can_hardware_interface.cpp, test/address_claim_tests.cpp
`add_can_lib_update_callback`, like many other callback methods, takes a `parentPointer` and stores said pointer in `CanLibUpdateCallbackInfo`.  However, unlike basically every other example of callbacks that I could find this meta-data is not actually passed to the callback itself, in fact the only place it seems to be used is in `remove_can_lib_update_callback` to confirm that you're removing the correct instance.
This updates the signatures and calls to actually pass the parent pointer to the callbacks themselves.
=> Actually pass the parent pointer to periodic updates.

isobus/src/can_transport_protocol.cpp
Fixed a crash that could happen when BAM is happening on the bus before address claiming is done, where the source control function has not been established yet.
=> [TP]: Fix a crash with BAM before address claiming 

hardware_integration/src/innomaker_usb2can_windows_plugin.cpp, isobus/CMakeLists.txt, isobus/include/isobus/isobus/can_NAME.hpp, isobus/include/isobus/isobus/can_address_claim_state_machine.hpp, isobus/include/isobus/isobus/can_badge.hpp, isobus/include/isobus/isobus/can_callbacks.hpp, isobus/include/isobus/isobus/can_extended_transport_protocol.hpp, isobus/include/isobus/isobus/can_managed_message.hpp, isobus/include/isobus/isobus/can_message.hpp, isobus/include/isobus/isobus/can_network_manager.hpp, isobus/include/isobus/isobus/can_partnered_control_function.hpp, isobus/include/isobus/isobus/can_protocol.hpp, isobus/include/isobus/isobus/can_transport_protocol.hpp, isobus/include/isobus/isobus/isobus_diagnostic_protocol.hpp, isobus/include/isobus/isobus/isobus_language_command_interface.hpp, isobus/include/isobus/isobus/isobus_task_controller_client.hpp, isobus/include/isobus/isobus/isobus_task_controller_client_objects.hpp, isobus/include/isobus/isobus/isobus_virtual_terminal_client.hpp, isobus/src/can_address_claim_state_machine.cpp, isobus/src/can_callbacks.cpp, isobus/src/can_extended_transport_protocol.cpp, isobus/src/can_internal_control_function.cpp, isobus/src/can_network_manager.cpp, isobus/src/can_transport_protocol.cpp, isobus/src/isobus_diagnostic_protocol.cpp, isobus/src/isobus_virtual_terminal_client.cpp
* Standardized all instances of `std::to_string` to `isobus::to_string`
* Fixed missing header files in CMake
* Fixed a number of trivial code smells from Sonar
=> [Core]: Address some code smells

CMakeLists.txt, examples/virtual_terminal/aux_functions/main.cpp, examples/virtual_terminal/aux_inputs/main.cpp, examples/virtual_terminal/version3_object_pool/main.cpp, hardware_integration/src/innomaker_usb2can_windows_plugin.cpp, isobus/include/isobus/isobus/isobus_virtual_terminal_client.hpp, isobus/src/isobus_virtual_terminal_client.cpp, test/event_dispatcher_tests.cpp, utility/CMakeLists.txt, utility/include/isobus/utility/event_dispatcher.hpp
With the new `EventDispatcher` class we should be able to implement listeners / callbacks in a more maintainable way. Why more maintainable?:
- The listeners automatically clean themselves up, so you don't have to worry about unregistering them
- There is a lot less code to write to when using callbacks in the library itself
- All types can be inserted due to the use of the template system
- No more typedeffed raw pointers to functions, which makes it a lot easier to register a callback as you don't have to look up the exact types you need to use.
If this sounds too good to be true, it probably is... The compiled `libIsobus.a` file size went from 13.5 MB to 15.8MB when compiling this PR compiled to the main branch. Not sure if this is game breaker?
Why this PR? I only changed the VT event …
=> [Core]: Add event dispatcher as more maintainable way of handling callbacks

isobus/include/isobus/isobus/isobus_virtual_terminal_client.hpp, isobus/src/isobus_virtual_terminal_client.cpp, test/vt_client_tests.cpp
This should help with optimizations at application level, as you now are able to know which mask is active. This can be used for example, to only send updates to a mask that is active.
=> [VT]: Add functions to get active masks

examples/diagnostic_protocol/main.cpp, examples/nmea2000/main.cpp, examples/pgn_requests/main.cpp, examples/task_controller_client/main.cpp, examples/transport_layer/main.cpp, examples/virtual_terminal/aux_functions/main.cpp, examples/virtual_terminal/aux_inputs/main.cpp, examples/virtual_terminal/version3_object_pool/main.cpp, hardware_integration/README.md, hardware_integration/include/isobus/hardware_integration/can_hardware_interface.hpp, hardware_integration/src/can_hardware_interface.cpp, isobus/include/isobus/isobus/can_hardware_abstraction.hpp, isobus/include/isobus/isobus/can_network_manager.hpp, isobus/src/can_network_manager.cpp, test/address_claim_tests.cpp, test/hardware_interface_tests.cpp, test/tc_client_tests.cpp, utility/include/isobus/utility/event_dispatcher.hpp
HardwareInterface:
- Major:
- Call `CANNetworkManager::update()` directly by default
- Call `CANNetworkManager::can_lib_process_rx_message()` directly by default
- Use `EventDispatcher<>` for periodic update event
- Use `EventDispatcher<isobus::HardwareInterfaceCANFrame>` for received/transmitted can frame event
- Add `get_periodic_update_interval()` to get interval between periodic updates
- Add more test cases for hardware interface
- Minor:
- Renamed `can_thread` to `update_thread` 
- Renamed `threadMutex` to `updateMutex`
- Renamed `canLibNeedsUpdate` to `stackNeedsUpdate`
- Renamed `periodicUpdateThread` to `wakeupThread`
- Renamed `canLibUpdatePeriod` to `periodicUpdateInterval`
- General optimizations to `update_thread_function` 
HardwareAbstraction:
- Renamed …
=> [Core]: Update hardware interface to use event dispatching system

isobus/include/isobus/isobus/can_stack_logger.hpp, isobus/src/can_stack_logger.cpp, isobus/src/isobus_task_controller_client.cpp
* Added variadic logging functions to the CAN Stack Logger.
This isn't the most efficient, but it does make our code much nicer. Based on code from @GwnDaan, slightly modified.
Closes #222
=> [Core]: Added additional logging templates, more like printf

isobus/include/isobus/isobus/isobus_virtual_terminal_client.hpp, isobus/src/isobus_virtual_terminal_client.cpp, test/vt_client_tests.cpp
- Added getters for the VT's control functions.
- Added a way to get the active working set master's address as reported by the VT server. 
- Added unit tests for these new functions, which required making the state machine states public similar to the TC client implementation.
=> [VT]: Added some additional getters to the VT client

hardware_integration/src/twai_plugin.cpp
This resolves an issue where the `isobus::CANHardwareInterface::stop();` function never returns when trying to stop the TWAI plugin while no new CAN messages are being received.
=> [HW]: Prevent rx thread from waiting forever with TWAI plugin

hardware_integration/src/can_hardware_interface.cpp, isobus/CMakeLists.txt, isobus/include/isobus/isobus/can_frame.hpp, isobus/include/isobus/isobus/can_hardware_abstraction.hpp, isobus/include/isobus/isobus/can_network_manager.hpp, isobus/src/can_frame.cpp, isobus/src/can_network_manager.cpp, test/core_network_management_tests.cpp
* Now the network manager will calculate the estimated busload over a rolling 1s time window using ten 100ms sample windows. 
* The average of best and worst case bit stuffing is used to approximate the load. 
* Also, I added some functionality to the hardware interface to tell the network manager whenever messages are emitted onto the bus. Both Tx and Rx messages must be considered to get a reasonably accurate bus load estimation.
Any sustained bus load > 70% should be considered potentially unstable. Perhaps we should log warnings in this case?
=> [Core]: Add busload calculation

hardware_integration/src/twai_plugin.cpp
As mentioned in https://github.com/ad3154/Isobus-plus-plus/discussions/229#discussioncomment-5660508, we want to initialize the members of the TWAI can message struct to their defaults. I think this PR should do the job. Even though I don't know if it makes any difference as it was using fine for me before, I think it is safer to zero-out the struct nonetheless.
=> [HW]: Initialize twai can message with zero values

CMakeLists.txt, isobus/CMakeLists.txt, isobus/include/isobus/isobus/can_general_parameter_group_numbers.hpp, isobus/include/isobus/isobus/isobus_shortcut_button_interface.hpp, isobus/src/isobus_shortcut_button_interface.cpp, test/isb_tests.cpp
* Added support for the AEF ISOBUS shortcut button, including sending as an ISB, and receiving states from other ISBs.
An ISB is essentially a command to all implements to enter a safe state. See the description located at https://www.isobus.net/isobus/pGNAndSPN/10936, ISO 11783-7, or https://www.aef-online.org/fileadmin/user_upload/Content/pdfs/AEF_One_Pager.pdf for more details.
=> [ISB]: Add support for ISOBUS shortcut button (ISB)

isobus/include/isobus/isobus/can_address_claim_state_machine.hpp, isobus/include/isobus/isobus/can_general_parameter_group_numbers.hpp, isobus/include/isobus/isobus/can_internal_control_function.hpp, isobus/include/isobus/isobus/can_message.hpp, isobus/include/isobus/isobus/can_network_manager.hpp, isobus/src/can_address_claim_state_machine.cpp, isobus/src/can_internal_control_function.cpp, isobus/src/can_message.cpp, isobus/src/can_network_manager.cpp, test/core_network_management_tests.cpp
* Added processing and use of the commanded address PGN. 
* Changed some CAN message getters to be const.
=> [Core]: Add support for J1939/ISOBUS commanded address message

isobus/include/isobus/isobus/isobus_virtual_terminal_client.hpp, isobus/src/can_network_manager.cpp, isobus/src/isobus_virtual_terminal_client.cpp, test/tc_client_tests.cpp, test/vt_client_tests.cpp
Sorry about the size of this PR, mostly it's white space.
* Add change attributes function for float attributes
* Removed calls to new/delete, replaced with vectors.
* Replaced C arrays with C++ arrays.
* Started adding more tests for the VT client (more to come...)
* Replaced VT client initializer list with in-class initializer where possible.
* Made lots of functions const.
* Fixed bugs related to endianness in some situations where floats were sent over the bus.
* Fixed a bug with drawing polygons indexing the message data incorrectly.
* Replaced some reinterpret casts with static casts.
* Fixed an issue with tests intermittently failing due to a missed call to the hardware interface "stop" function
* Removed an unused variable from the network manager
=> [VT]: VT client cleanup and ability to change float attributes

isobus/include/isobus/isobus/isobus_virtual_terminal_client.hpp, isobus/src/isobus_virtual_terminal_client.cpp
* Fixed a missing `const` causing some ambiguity when calling send_change_attribute
=> [VT]: Fixed a missing const

hardware_integration/include/isobus/hardware_integration/mcp2515_can_interface.hpp, hardware_integration/src/mcp2515_can_interface.cpp, hardware_integration/src/twai_plugin.cpp
Previously the MCP2515 plugin wasn't always transmitting or receiving CAN messages in the correct order, this should be fixed in the PR. The changes made to achieve this:
- Use an cached index for reading the correct buffer when messages 'rollover'
- Log to the user when a frame failed to transmit, this is done when sending the next message to preserve communication speed
- Only use **one** of the three available buffers for transmitting. I'm not sure how to implement multiple transmitting buffers while keeping the messages transmitted in the correct order. Any ideas are welcome!
Also changed the timeout for transmitting/receiving messages with the TWAI plugin to 100ms. This might be useful for example when no CANbus is connected.
=> [HW]: Make MCP2515 plugin transmitting and receiving reliable

CMakeLists.txt, examples/diagnostic_protocol/main.cpp, isobus/CMakeLists.txt, isobus/include/isobus/isobus/can_general_parameter_group_numbers.hpp, isobus/include/isobus/isobus/isobus_diagnostic_protocol.hpp, isobus/include/isobus/isobus/isobus_functionalities.hpp, isobus/src/isobus_diagnostic_protocol.cpp, isobus/src/isobus_functionalities.cpp, test/cf_functionalities_tests.cpp
* This adds support for sending the CF Functionalities message as part of the diagnostic protocol class.
* The new class will automatically respond to requests from ANY ecu, either as a broadcast or point-to-point for the "Control Function Functionalities" PGN (0xFC8E, 64654)
* ISOBUS ECUs are required to support this message, so by default, we will report every consumer of our library as a "Minimum Control Function" of "generation 1" unless configured otherwise (if you are using the diagnostic protocol).
* In general you will want your application to configure this appropriately for what you are using. If you are using the VT client, you should configure this message to send "Universal Terminal Working Set" as supported. If you are using the TC client, same thing, you will want to report …
=> [DP]: Add ISOBUS Control Function Functionalities Message

isobus/include/isobus/isobus/can_callbacks.hpp, isobus/include/isobus/isobus/can_network_manager.hpp, isobus/include/isobus/isobus/can_partnered_control_function.hpp, isobus/include/isobus/isobus/isobus_functionalities.hpp, isobus/include/isobus/isobus/nmea2000_fast_packet_protocol.hpp, isobus/src/can_callbacks.cpp, isobus/src/can_network_manager.cpp, isobus/src/can_partnered_control_function.cpp, isobus/src/nmea2000_fast_packet_protocol.cpp
This allows users to register callbacks for messages from a partner that are filtered by destination internal control function.
This essentially helps you only get callbacks for messages destined for one specific ICF if you have multiple, making a multi-ECU application easier/nicer.
Closes #206.
=> [Core]: Add internal CF filtering option for partner CF callbacks

CMakeLists.txt, examples/guidance/CMakeLists.txt, examples/guidance/console_logger.cpp, examples/guidance/main.cpp, hardware_integration/src/virtual_can_plugin.cpp, isobus/include/isobus/isobus/isobus_guidance_interface.hpp, isobus/src/isobus_guidance_interface.cpp, test/guidance_tests.cpp
**Main changes:**
- Added read-only example
- Added a `changed` param to the event dispatchers
- Added the ability to choose which message you want to send periodically (Most applications don't want to sent both afaik)
**Other changes:**:
- Renamed a few of the variables/functions/classes. I tried to make the naming more consistent throughout the guidance interface. Now the main interface is called "AgriculturalGuidanceInterface" and all the other naming have the "Agriculture" part removed. Before, the word was not really consistently used as it was present in some places, while not in others.
- Added small timeout to the VirtualCANInterface, such that when a test fails to read a frame, it doesn't hang forever.
Sorry for changing so much, I happened to come across this while making the …
=> [Guidance]: Add basic read-only example

CMakeLists.txt, examples/guidance/CMakeLists.txt, examples/guidance/console_logger.cpp, examples/guidance/main.cpp, hardware_integration/src/virtual_can_plugin.cpp, isobus/CMakeLists.txt, isobus/include/isobus/isobus/can_general_parameter_group_numbers.hpp, isobus/include/isobus/isobus/isobus_guidance_interface.hpp, isobus/src/isobus_guidance_interface.cpp, test/guidance_tests.cpp
* Added interface for sending and receiving guidance messages.
This PR defines an interface for sending and receiving ISOBUS guidance messages.
These messages are used to steer ISOBUS compliant machines, steering valves, and implements in general.
The interface supports any number of senders of the guidance curvature command message, any number of Agricultural Guidance Machine Info messages, and also supports transmitting both messages.
**Please use extreme care if you try to steer a machine with this interface!** Remember that this library is licensed under The MIT License, and that by obtaining a copy of this library and of course by attempting to steer a machine with it, you are agreeing to our license. The developers of Isobus++ will not help you reverse engineer how to steer any …
=> Add ISOBUS Guidance (Steering) Interface

isobus/include/isobus/isobus/isobus_virtual_terminal_objects.hpp, isobus/include/isobus/isobus/isobus_virtual_terminal_server_managed_working_set.hpp, isobus/src/isobus_virtual_terminal_objects.cpp, isobus/src/isobus_virtual_terminal_server_managed_working_set.cpp
Hi, this is my first pull-request and just a small bug fix that prevents a segmentation fault if the vtObjectTree is a nullptr.
Additionally a warning due to an out-of-order initializier list is fixed.
=> [VT]: VT server managed working set bugfix

isobus/include/isobus/isobus/can_extended_transport_protocol.hpp, isobus/include/isobus/isobus/can_message.hpp, isobus/include/isobus/isobus/can_transport_protocol.hpp, isobus/include/isobus/isobus/nmea2000_fast_packet_protocol.hpp, isobus/src/can_extended_transport_protocol.cpp, isobus/src/can_message.cpp, isobus/src/can_transport_protocol.cpp, isobus/src/nmea2000_fast_packet_protocol.cpp
This PR is bugfix for messages being transported by data chunk callbacks using any transport protocol. Their message length was recognized as 0 due to the removal of CANLibManagedMessage in #255.
- Add `frameChunkCallbackMessageLength` to all transporting protocol session classes
- Add utility function `get_message_data_length` to all transporting protocol session classes to determine the correct message length considering both data chunk callbacks and the normal copied message data.
- Also changed the message length/indexes in CANMessage from `size_t` to `uint32_t` as it can't exceed the maximum message length of ETP: 117440505
=> [TP]: Add missing message length for frame chunk callback

examples/guidance/CMakeLists.txt
Add linking to Threads::Threads in guidance example
=> [Examples]: Fix missing linkage to Threads::Threads in guidance example

isobus/include/isobus/isobus/can_address_claim_state_machine.hpp, isobus/include/isobus/isobus/can_control_function.hpp, isobus/include/isobus/isobus/can_internal_control_function.hpp, isobus/include/isobus/isobus/can_network_manager.hpp, isobus/src/can_address_claim_state_machine.cpp, isobus/src/can_control_function.cpp, isobus/src/can_internal_control_function.cpp, isobus/src/can_network_manager.cpp, isobus/src/isobus_virtual_terminal_client.cpp, test/core_network_management_tests.cpp
* Added active control function pruning so that if a control function fails to claim after a request for the address claim PGN, we move that control function to the inactive list and invalidate its address. 
This was always meant to be a part of how we manage address claiming, but for whatever reason got left behind. This greatly increases the reliability of checking a control function's address being valid.
* Fixed a random crash in unit tests.
* Added additional logging to the address claim state machine to more clearly describe what is happening.
Closes #192
=> [Core]: Improved lost CF pruning

isobus/include/isobus/isobus/isobus_language_command_interface.hpp, isobus/include/isobus/isobus/isobus_task_controller_client_objects.hpp, isobus/src/isobus_language_command_interface.cpp
I tried to compile the stack on fedora with  gcc 13 and had some missing includes.
=> Add missing includes for gcc 13

isobus/include/isobus/isobus/isobus_virtual_terminal_client.hpp, isobus/src/isobus_virtual_terminal_client.cpp
* Changed all VT client shutdowns to be graceful when possible.
- Now we'll send the delete object pool message when terminating the VT client.
- This has several benefits! Most importantly, it allows you to bypass the 3 second status message timeout, but it also will probably stop most terminals from complaining when you close your application, as terminals will see it as a graceful disconnect rather than a timeout.
- This does not remove your object pool from the terminal's non volatile memory, it only tells the VT you are done using it for now.
* Added a restart routine for the VT client.
- Useful if you want to gracefully shutdown the connection and restart it without calling terminate and initialize.
* Fixed issue where if you called terminate, then initialize, the VT client would be …
=> [VT] Graceful shutdown/restart, improvements to some object pool uploads

isobus/include/isobus/isobus/isobus_language_command_interface.hpp, isobus/src/isobus_language_command_interface.cpp, test/language_command_interface_tests.cpp
* Added support for SPN 9731 in the language command PGN.
This is a command sent to all ECUs specifying the operator's desired language dialect.
ISO 11783 networks use alpha-2 country codes in accordance with ISO 3166-1. (7 bit upper-case ISO Latin 1 characters)
When both characters are set to all 1’s (0xFFs) it indicates that no country code is specified.
=> [VT/TC]: Add country code to language command interface

isobus/src/isobus_guidance_interface.cpp, isobus/src/isobus_maintain_power_interface.cpp, isobus/src/isobus_shortcut_button_interface.cpp, isobus/src/isobus_speed_distance_messages.cpp, test/event_dispatcher_tests.cpp, utility/include/isobus/utility/event_dispatcher.hpp
Objects that don't have move semantics defined should not be moved as it will simply just copy the object. Instead we can just pass it by reference-to-const.
Hence we now have two functions in the EventDispatcher (since overloading is not possible):
- `call()`: notify the listeners using reference-to-const
- `invoke()`: notify the listeners using move semantics (or the in-place constructor)
For details, see [this sonarcloud explanation](https://sonarcloud.io/project/issues?fileUuids=AYglNneU6edfKl3pa05B&resolved=false&types=CODE_SMELL&id=ad3154_ISO11783-CAN-Stack&open=AYglNn-v6edfKl3pa05Q&tab=why)
=> [Core]: Differentiate rvalues/lvalues in EventDispatcher

isobus/include/isobus/isobus/isobus_device_descriptor_object_pool.hpp, isobus/src/can_transport_protocol.cpp, isobus/src/isobus_device_descriptor_object_pool.cpp, isobus/src/isobus_task_controller_client_objects.cpp, test/ddop_tests.cpp
* Added functionality to take a binary DDOP and create an AgIsoStack DDOP from it. This will be an important feature to have if/when we add a TC server.
* Added a function to allow getting DDOP objects by index, which will allow a TC server to search all objects without having to interrogate all 65535 object IDs in the DDOP.
=> [DDOP]: Add DDOP deserializer

isobus/src/can_network_manager.cpp, isobus/src/can_transport_protocol.cpp
* Fixes a crash where I was null-ing out an evicted CF right before I tried to access it to print a log statement.
* Fixed an issue in transport protocol where we were allowing >1 BAM transmit sessions to be created at the same time for a given internal control function due to us using only the destination specific session getter.
=> [Core/TP]: Fix a crash on CF eviction, and fix TP BAM session overlap

examples/diagnostic_protocol/main.cpp, isobus/include/isobus/isobus/can_control_function.hpp, isobus/include/isobus/isobus/isobus_diagnostic_protocol.hpp, isobus/src/can_network_manager.cpp, isobus/src/can_transport_protocol.cpp, isobus/src/isobus_diagnostic_protocol.cpp, test/core_network_management_tests.cpp, test/diagnostic_protocol_tests.cpp, test/language_command_interface_tests.cpp, test/tc_client_tests.cpp
**Major**:
- Refactor away from the diagnosticProtocolList and let the user create objects instead
- Refactor away from extending CANLibProtocol to be more inline with newly added interfaces (Guidance/speed/maintain power) to have a more "The library should only do work when it is explicitly asked to" experience.
- Add dedicated NetworkType configuration parameter
- Introduced `initialize` / `terminate` as replacements for `assign_...` / `deassign_....`
**Minor:**
- Use in-class initializers where possible
- Fixed several typos
- Apply reference-to-const variables and const functions where possible
- Remove redundant case ' clauses'
- Remove redundant parenthesis
- Moved `parse_j1939_network_states` function from public to private
@ad3154, note that I don't have any way of testing if this …
=> [DP] Refactor away from diagnosticProtocolList

isobus/include/isobus/isobus/can_internal_control_function.hpp, isobus/include/isobus/isobus/can_network_manager.hpp, isobus/include/isobus/isobus/can_partnered_control_function.hpp, isobus/src/can_control_function.cpp, isobus/src/can_internal_control_function.cpp, isobus/src/can_network_manager.cpp, isobus/src/can_partnered_control_function.cpp
This PR moves the static lists located in the InternalControlFunction and PartneredControlFunction classes to a centralized place in the manager class. This should make it easier to refactor away from the singleton pattern for the CANNetworkManager.
=> [CF]: Remove static lists from control functions

isobus/src/isobus_language_command_interface.cpp, test/cf_functionalities_tests.cpp
Fixes some issues compiling under Clang14 on Mac
* Fix passing non-trivial (string) argument to variadic parameter. 
* Remove unneeded 'this' captures in some test lambdas. 
Tested with Clang 14.0.0 x86_64-apple-darwin21.6.0
=> [VT/TC/Tests]: Fix some Clang 14 compilation issues

isobus/include/isobus/isobus/isobus_task_controller_client.hpp, isobus/src/isobus_task_controller_client.cpp, test/tc_client_tests.cpp
* Added functions to allow retrieving the control functions being used by the task controller interface.
=> [TC]: Add getters for TC client interfaces control functions

isobus/include/isobus/isobus/isobus_task_controller_client.hpp, isobus/src/isobus_task_controller_client.cpp, test/tc_client_tests.cpp
* Added a way for applications that have on-change triggers in their DDOP to tell the TC client interface that it should send a value command to the TC server with an updated value on its next update.
(cherry picked from commit 06e266556107adb57d2e7cc1aef7f0032ce0b717)
=> [TC]: Added a way to request an on-change trigger

examples/diagnostic_protocol/main.cpp, examples/pgn_requests/main.cpp, isobus/include/isobus/isobus/can_internal_control_function.hpp, isobus/include/isobus/isobus/can_parameter_group_number_request_protocol.hpp, isobus/include/isobus/isobus/isobus_diagnostic_protocol.hpp, isobus/include/isobus/isobus/isobus_functionalities.hpp, isobus/src/can_internal_control_function.cpp, isobus/src/can_parameter_group_number_request_protocol.cpp, isobus/src/isobus_diagnostic_protocol.cpp, isobus/src/isobus_functionalities.cpp, isobus/src/isobus_language_command_interface.cpp, test/cf_functionalities_tests.cpp, test/diagnostic_protocol_tests.cpp, test/language_command_interface_tests.cpp, test/tc_client_tests.cpp, test/vt_client_tests.cpp
Like with the DiagnosticProtocol's static list removal in #281, this PR removes the static list in the `ParameterGroupNumberRequestProtocol` and instead let the application handle the objects themselves. 
Though a drawback of this approach I found, is that every other interface that requires "pgn requests" support (e.g. the LanguageInterface/DiagnosticProtocol) need to be fed with a shared_ptr to a `ParameterGroupNumberRequestProtocol` object. We could instead house the list of `ParameterGroupNumberRequestProtocol` inside the CANNetworkManager **or** assign to each InternalControlFunction an optionally dedicated `ParameterGroupNumberRequestProtocol` object (that get's automatically constructed/deconstructed when needed)? 
On the other hand, we can also just leave it as is, but then we …
=> [RP]: Remove internal static pgn request protocol list

isobus/include/isobus/isobus/isobus_device_descriptor_object_pool.hpp, isobus/src/isobus_device_descriptor_object_pool.cpp
* Added a check to make sure ECU NAME matches DDOP NAME when deserializing a DDOP.
* Added a way to skip checking against an ECU's actual NAME, which could be useful when just doing offline DDOP creation or parsing.
=> [DDOP]: Added missing checks for NAME when deserializing a DDOP

isobus/include/isobus/isobus/can_internal_control_function.hpp, isobus/include/isobus/isobus/can_partnered_control_function.hpp, isobus/src/can_internal_control_function.cpp, isobus/src/can_partnered_control_function.cpp
Made the constructors of a few objects public with an added badge to try and resolve some ESP specific compilation issues. They can still only be instantiated with the factory functions due to the badge.
(cherry picked from commit c0e392eae95102691f653e2431ea527c4596c3d0)
=> [Core]: Made ICF and Partner Control Function's constructors public

isobus/include/isobus/isobus/isobus_task_controller_client_objects.hpp, isobus/src/isobus_task_controller_client_objects.cpp, test/ddop_tests.cpp
* This allows modifying some DDOP objects after they're created, whereas previously you couldn't modify them once constructed.
As far as I know, there wasn't really a reason to disallow changing most of the objects' fields, and allowing it makes real-time editing of the DDOP a lot easier.
=> [DDOP]: Add setters for most TC object values

isobus/include/isobus/isobus/isobus_device_descriptor_object_pool.hpp, isobus/src/isobus_device_descriptor_object_pool.cpp, test/ddop_tests.cpp
* Added a function to allow removing "DET" child references.
=> [DDOP]: Added a way to remove device element object child references

CMakeLists.txt
This lets users choose in the consuming application what build type they want. 
This was probably just an anachronism from early development.
=> [Meta]: Don't force CMake build type to be debug

examples/task_controller_client/main.cpp, isobus/src/can_network_manager.cpp, test/core_network_management_tests.cpp
Fixed situations where consecutive address claims by partners that were very similar based on NAME filters would cause an already valid partner to be overwritten with a different partner's address data. Also, locked TC example to use the primary TC.
Closes #310
=> [#310]: Fix incorrect relocation of partner CFs with very similar NAME filters

examples/transport_layer/main.cpp, isobus/include/isobus/isobus/can_extended_transport_protocol.hpp, isobus/include/isobus/isobus/can_network_configuration.hpp, isobus/include/isobus/isobus/can_network_manager.hpp, isobus/include/isobus/isobus/can_transport_protocol.hpp, isobus/src/can_extended_transport_protocol.cpp, isobus/src/can_network_configuration.cpp, isobus/src/can_network_manager.cpp, isobus/src/can_transport_protocol.cpp
This is based on discussion #307 and adds a way for a user to slow down the speed of our transport sessions to reduce the overall busload if you want, or help take some load off of your CAN adapter.
- Added a way to throttle ETP max data packets per network manager update.
- Added a way to throttle the number of ETP data frames per EDPO message.
- Moved some ETP constructor initializers to the in-class initializer.
- Made `CANNetworkConfiguration` less static.
- Added a way to throttle TP max data frames per network manager update.
- Moved some TP constructor initializers to the in-class initializer.
- Fixed some typos
=> [TP/ETP]: Add options for transport layer throttling

isobus/include/isobus/isobus/can_callbacks.hpp, isobus/include/isobus/isobus/can_network_manager.hpp, isobus/src/can_network_manager.cpp, test/core_network_management_tests.cpp
* This addresses issue #210 and provides a way to get callbacks from the network manager when a control function changes state.
* Overall, this reduces the need to poll the state of your partners in a consuming application.
* Also fixed some typos.
Closes #210
=> [Core]: Added a way to get callbacks when any CF goes online or offline

examples/task_controller_client/section_control_implement_sim.cpp, isobus/src/isobus_device_descriptor_object_pool.cpp, test/core_network_management_tests.cpp, test/ddop_tests.cpp, test/tc_client_tests.cpp
* Added validation of DET child references' object types. Added sanity checks on other objects' child types even though those are  essentially forced to be correct.
* Reworked a couple things in the unit tests to prevent some tests from interfering with other tests specifically when not using CTest.
Closes #316
=> [DDOP]: Add validation for DDOP object child references

isobus/include/isobus/isobus/can_network_manager.hpp, isobus/src/can_control_function.cpp, isobus/src/can_internal_control_function.cpp, isobus/src/can_network_manager.cpp, isobus/src/can_partnered_control_function.cpp
* Added overloads of on_control_function_created that take all variants of CF badges to fix compilation issues with PlatformIO + ESP32.
I tested the alternate approach of changing CANLibBadge's member to `protected`, but that didn't seem to solve the issue.
This fix I tested myself with platform IO.
=> [#322]: ESP32 + Platform IO Compilation Fixes

isobus/src/isobus_device_descriptor_object_pool.cpp
- Fixed an issue where a device element object's element number would be incorrectly truncated, which could corrupt a DDOP on deserialization if any element number was greater than 255.
- Fixed two broken log statements in the DDOP class.
=> [DDOP]: Fixed a truncation in DDOP deserializer

isobus/include/isobus/isobus/can_address_claim_state_machine.hpp, isobus/include/isobus/isobus/can_internal_control_function.hpp, isobus/include/isobus/isobus/can_network_manager.hpp, isobus/include/isobus/isobus/isobus_diagnostic_protocol.hpp, isobus/src/can_address_claim_state_machine.cpp, isobus/src/can_internal_control_function.cpp, isobus/src/can_network_manager.cpp, isobus/src/isobus_diagnostic_protocol.cpp, test/diagnostic_protocol_tests.cpp
ISO11783-5 states that an address violation occurs when two control functions use the same source address.
If a CF receives a message other than an address-claim which uses the CF's own source address, then the CF must:
- Send an address claim to the broadcast address
- Set a DTC active with SPN = 2000 + source address and FMI 31 (condition exists)
This PR does that!
- Add a way for users to get callbacks when an address violation occurs that affects an internal control function
- Added some logic to the address claim state machine to resend the address claim message when address claim violations happen
- Added some logic to the diagnostic protocol so that if the user has initialized it, the stack will automatically set the proper DTC active when address violations occur. Users can clear …
=> [Core/DP]: Add address violation handling

.github/workflows/build.yml
- Upgrade sonar action from `v1` to `v2`, I assume this will fix the Java version warning (replaces #309) 
- Removed the "approve" step. This should speed up the CI process as it won't require human input and by using the normal `pull_request` we don't risk any future security risks. I think this outweighs the drawback that PR's created from forks do **not** run the Sonar analysis (though they will build, test and lint immediately). Opinions on this welcome
- Also made windows and mac-os jobs run tests
Note that I haven't tested this
=> [CI]: remove approve step and upgrade sonar

.github/workflows/build.yml
Tests were failing in the CI pipeline because it couldn't catch any asserts as it was being build in "Release" mode, which optimizes out the asserts. I think it's reasonable to build the pipeline in debug to pass the unit tests, opinions?
=> Switch to debug builds in CI to catch asserts in unit tests

isobus/src/can_extended_transport_protocol.cpp
- Fixed a boundary check when receiving an ETP session when reconstructing the message payload in the final frame of the session.
=> [ETP]: Fixed an issue where receiving some ETP sessions could cause a crash

isobus/src/isobus_virtual_terminal_client.cpp
- Fixed an issue where uploading more than one object pool to a VT would cause only the first pool to be completed.
It's fairly common to break up an object pool into smaller parts and upload them separately, such as having a pool for the the main content, a pool for soft keys, and a pool for each language you support. There was an issue where only the first pool would complete the upload process properly which should now be fixed!
Tested with 5 object pools as shown below.
=> [VT]: Fixed issues uploading multiple object pool chunks to a VT

CMakeLists.txt, examples/diagnostic_protocol/CMakeLists.txt, examples/guidance/CMakeLists.txt, examples/nmea2000/CMakeLists.txt, examples/pgn_requests/CMakeLists.txt, examples/task_controller_client/CMakeLists.txt, examples/transport_layer/CMakeLists.txt, examples/virtual_terminal/aux_functions/CMakeLists.txt, examples/virtual_terminal/aux_inputs/CMakeLists.txt, examples/virtual_terminal/version3_object_pool/CMakeLists.txt, hardware_integration/CMakeLists.txt, isobus/CMakeLists.txt, utility/CMakeLists.txt
- Replaced setting `CMAKE_CXX_STANDARD` and `CMAKE_CXX_STANDARD_REQUIRED` with `set_target_properties` to avoid unintentionally affecting top level consuming projects.
This seems like it's the more modern way of setting the version so as to not affect the global C++ settings in a consuming project.
=> [Meta]: Modernized setting the C++ version in CMake

README.md
- Added missing supported CAN plugins to the list.
- Fixed some outdated compilation commands.
- Added instructions to acquire Git in addition to CMake, especially for Windows. 
- Added instructions for how to integrate the library with FetchContent.
- Clarified that we don't officially provide pre-compiled versions of the library.
=> [Meta]: Updated some outdated README info

isobus/include/isobus/isobus/isobus_language_command_interface.hpp, isobus/src/isobus_language_command_interface.cpp, test/language_command_interface_tests.cpp
- Added the ability to respond to requests for language commands. 
- Added setters for language command values.
This functionality will be needed for VT and TC servers.
=> [VT/TC]: Language Command Sending and Setters

README.md, examples/diagnostic_protocol/main.cpp, examples/guidance/main.cpp, examples/nmea2000/fast_packet_protocol/main.cpp, examples/nmea2000/nmea2000_generator/main.cpp, examples/nmea2000/nmea2000_parser/main.cpp, examples/pgn_requests/main.cpp, examples/task_controller_client/main.cpp, examples/transport_layer/main.cpp, examples/virtual_terminal/aux_functions/main.cpp, examples/virtual_terminal/aux_inputs/main.cpp, examples/virtual_terminal/esp32_platformio_object_pool/src/main.cpp, examples/virtual_terminal/version3_object_pool/main.cpp, sphinx/source/Tutorials/Adding a Destination.rst, sphinx/source/Tutorials/ESP32 PlatformIO.rst, sphinx/source/Tutorials/Receiving Messages.rst, sphinx/source/Tutorials/The ISOBUS Hello World.rst, sphinx/source/Tutorials/Virtual Terminal Basics.rst, test/core_network_management_tests.cpp, test/diagnostic_protocol_tests.cpp, test/guidance_tests.cpp, test/language_command_interface_tests.cpp, test/maintain_power_tests.cpp, test/nmea2000_message_tests.cpp, test/speed_distance_message_tests.cpp, test/vt_client_tests.cpp
- Changed all example manufacturer codes to our code 1407 🎉
- Updated README with guidance on use of our manufacturer code.
=> [Meta/Examples]: Update all example manufacturer codes to 1407 (Open-Agriculture)

CMakeLists.txt, isobus/CMakeLists.txt, isobus/include/isobus/isobus/can_constants.hpp, isobus/include/isobus/isobus/isobus_virtual_terminal_objects.hpp, isobus/src/isobus_virtual_terminal_objects.cpp, test/vt_object_tests.cpp
This is intended to be used with a VT server (coming soon? ) or with an object pool editor program. I wanted to open a PR for the ones I have done before the file gets even larger.
- Added classes to represent most VT objects.
Supported objects so far:
- Working Set
- Data Mask
- Alarm Mask
- Container
- Soft Key mask
- Key
- Key Group
- Button
- Input Boolean
- Input String
- Input Number
- Input List
- Output String
- Output Number
- Output List
- Output Line
- Output Rectangle
- Output Ellipse
- Output Polygon
- Output Meter
- Output Linear Bar Graph
- Output Arched Bar Graph
- Picture Graphic
- Number Variable
- String Variable
- Font Attributes
- Line Attributes
- Fill Attributes
- Input Attributes
- Extended Input Attributes
- Object Pointer
- External Object Pointer
- Macro
- …
=> [VT]: Add Virtual Terminal Object Classes

isobus/include/isobus/isobus/nmea2000_message_definitions.hpp
This gave an error building with GCC13.2.1 on Fedora
=> Add missing <string> include in NMEA2000 interface

isobus/include/isobus/isobus/isobus_task_controller_client.hpp, isobus/src/isobus_task_controller_client.cpp, test/tc_client_tests.cpp
- Added a way to reset a connection with a task controller server manually. 
- Added a way to trigger an update (and reupload) of a DDOP. 
- Fixed a crash/exception when trying to call the TC client terminate function from within the worker thread.
Closes #354 
Closes #355
=> [TC]: Add restart and reupload capabilities to TC client

isobus/include/isobus/isobus/isobus_virtual_terminal_client.hpp, isobus/src/isobus_virtual_terminal_client.cpp, test/vt_client_tests.cpp
This PR adds a command transmit queue for the VT client. Should allow for a more reliable out-of-the-box command sending mechanism.
Closes #362
=> [VT]: Add command queue

isobus/include/isobus/isobus/isobus_virtual_terminal_client.hpp, isobus/src/isobus_virtual_terminal_client.cpp, test/vt_client_tests.cpp
updates all VT client messages to priority 5 as stated in #378
=> update all VT client messages to priority 5 done

isobus/include/isobus/isobus/isobus_virtual_terminal_objects.hpp, isobus/src/isobus_virtual_terminal_objects.cpp
- Added a way to store and associate macro data with VT objects. 
- Fixed a bug where an output string's value attribute setter was checking the wrong object type.
=> [VT]: Add VT Event enum and a way to associate macros with VT objects

CMakeLists.txt, examples/diagnostic_protocol/CMakeLists.txt, examples/guidance/CMakeLists.txt, examples/nmea2000/fast_packet_protocol/CMakeLists.txt, examples/nmea2000/nmea2000_generator/CMakeLists.txt, examples/nmea2000/nmea2000_parser/CMakeLists.txt, examples/pgn_requests/CMakeLists.txt, examples/task_controller_client/CMakeLists.txt, examples/transport_layer/CMakeLists.txt, examples/virtual_terminal/aux_functions/CMakeLists.txt, examples/virtual_terminal/aux_inputs/CMakeLists.txt, examples/virtual_terminal/version3_object_pool/CMakeLists.txt, hardware_integration/CMakeLists.txt, hardware_integration/src/can_hardware_interface.cpp, hardware_integration/src/can_hardware_interface_single_thread.cpp, isobus/CMakeLists.txt, isobus/include/isobus/isobus/isobus_task_controller_client.hpp, isobus/include/isobus/isobus/isobus_virtual_terminal_client.hpp, isobus/src/can_internal_control_function.cpp, test/diagnostic_protocol_tests.cpp, test/language_command_interface_tests.cpp, test/tc_client_tests.cpp, test/vt_client_tests.cpp, utility/CMakeLists.txt
This is an attempt to expand compatibility with the consumers of the Arduino library, one of whom reported that `std::make_unique` was causing them to be unable to compile the library.
https://github.com/Open-Agriculture/AgIsoStack-Arduino/issues/7
Interested to hear thoughts on this... I know we are targeting at least C++14 (which is when make_unique was introduced) but this seems like a fairly minor change to bring the Arduino lib back down to C++11
=> Removed references to std::make_unique

sonar-project.properties
Forces sonar's checks to cap out at C++ 11 so we don't get irrelevant code smells.
=> [Meta]: Force sonar's C++ version to 11

test/CMakeLists.txt, test/cf_functionalities_tests.cpp, test/core_network_management_tests.cpp, test/diagnostic_protocol_tests.cpp, test/helpers/control_function_helpers.cpp, test/helpers/control_function_helpers.hpp, test/helpers/messaging_helpers.cpp, test/helpers/messaging_helpers.hpp
This should provide an easier, and better maintainable way of defining CAN communication in unit-tests
=> Add CAN messaging helpers

examples/nmea2000/fast_packet_protocol/main.cpp, hardware_integration/include/isobus/hardware_integration/virtual_can_plugin.hpp, hardware_integration/src/virtual_can_plugin.cpp, isobus/include/isobus/isobus/can_identifier.hpp, isobus/include/isobus/isobus/can_message.hpp, isobus/src/can_identifier.cpp, isobus/src/can_message.cpp, isobus/src/can_network_manager.cpp, isobus/src/isobus_guidance_interface.cpp, isobus/src/isobus_shortcut_button_interface.cpp, isobus/src/isobus_speed_distance_messages.cpp, isobus/src/isobus_virtual_terminal_client.cpp, isobus/src/nmea2000_message_interface.cpp, sphinx/source/Tutorials/Transport Layer.rst, test/diagnostic_protocol_tests.cpp, test/language_command_interface_tests.cpp, test/vt_client_tests.cpp
With this change, **all** compilers will throw errors when conversion is done implicitly on the identitier enums. It prevents us from making subtle mistakes where conversion shouldn't have happened.
=> Remove implicit conversion for identifier priority

isobus/include/isobus/isobus/isobus_virtual_terminal_client.hpp, isobus/src/isobus_virtual_terminal_client.cpp, test/vt_client_tests.cpp
To comply with the standard, we must wait for responses from the VT server before sending the next command. This PR implements that behaviour
=> [VT] Wait on response before processing next command

CMakeLists.txt, isobus/include/isobus/isobus/can_network_manager.hpp, isobus/src/can_network_manager.cpp, test/CMakeLists.txt, test/cf_functionalities_tests.cpp, test/core_network_management_tests.cpp, test/diagnostic_protocol_tests.cpp, test/guidance_tests.cpp, test/helpers/control_function_helpers.cpp, test/helpers/control_function_helpers.hpp, test/helpers/messaging_helpers.cpp, test/helpers/messaging_helpers.hpp, test/isb_tests.cpp, test/language_command_interface_tests.cpp, test/maintain_power_tests.cpp, test/nmea2000_message_tests.cpp, test/speed_distance_message_tests.cpp, test/tc_client_tests.cpp, test/vt_client_tests.cpp
Basically bootstrapped unit-test helpers with 3 functions:
- claim_internal_control_function
- force_claim_partnered_control_function
- create_extended_can_id
I'm curious about opinion of others on this
=> Introduce helpers in unit tests

isobus/include/isobus/isobus/isobus_virtual_terminal_client.hpp, isobus/src/isobus_virtual_terminal_client.cpp
Closes #381 
- renamed `get_vt_version_supported` to `is_vt_version_supported`, for clarity
- added all activation message responses
=> Add activation message responses

hardware_integration/src/can_hardware_interface.cpp, hardware_integration/src/can_hardware_interface_single_thread.cpp, hardware_integration/src/mac_can_pcan_plugin.cpp, hardware_integration/src/pcan_basic_windows_plugin.cpp, hardware_integration/src/socket_can_interface.cpp, hardware_integration/src/spi_interface_esp.cpp, hardware_integration/src/spi_transaction_frame.cpp, hardware_integration/src/sys_tec_windows_plugin.cpp, hardware_integration/src/toucan_vscp_canal.cpp, hardware_integration/src/twai_plugin.cpp, isobus/src/isobus_task_controller_client.cpp, isobus/src/isobus_virtual_terminal_client.cpp, isobus/src/nmea2000_fast_packet_protocol.cpp
I skipped TP/ETP because I'm in the process of rewriting it and not changing it there will prevent cumbersome merge conflicts :)
=> Use shorter logging form everywhere except in TP/ETP

examples/virtual_terminal/aux_functions/main.cpp, examples/virtual_terminal/aux_inputs/main.cpp, examples/virtual_terminal/esp32_platformio_object_pool/src/main.cpp, examples/virtual_terminal/version3_object_pool/main.cpp, hardware_integration/CMakeLists.txt, isobus/include/isobus/isobus/isobus_virtual_terminal_client.hpp, isobus/src/isobus_virtual_terminal_client.cpp, isobus/src/isobus_virtual_terminal_objects.cpp, isobus/src/nmea2000_message_definitions.cpp, sphinx/source/Tutorials/Virtual Terminal Basics.rst, test/vt_client_tests.cpp
- Removed unused variables
- Fixed a move that prevented copy elision
- Changed the severity of one CMake message
=> [Misc]: Fixed warnings when compiling for Apple

hardware_integration/include/isobus/hardware_integration/socket_can_interface.hpp, hardware_integration/src/socket_can_interface.cpp
This PR makes it easier to change which CAN interface a SocketCAN plugin cares about at runtime rather than only in the constructor. This makes it easier to change at runtime in AgISOVirtualTerminal.
=> [HW]: Allow changing socket CAN name at runtime

isobus/include/isobus/isobus/isobus_virtual_terminal_server.hpp, isobus/src/isobus_virtual_terminal_server.cpp
Also renamed made `processMacro` to `process_macro` to follow snake_case convention of repository
=> Less duplication for macro execute/process commands

.github/workflows/linting.yml, README.md, doxyfile, sphinx/source/Developer Guide.rst, sphinx/source/Installation.rst, sphinx/source/Tutorials/The ISOBUS Hello World.rst, sphinx/source/index.rst
Moved some of the more use case specific stuff from the main README, to the sphinx site to not overwhelm a first time viewer. While still allowing more detailed instructions in a central place on the site. 
I think adding the quick links and a catch phrase also looks nice at the top of our README, but I'd like thoughts on that. Replacing the 3 top images with a catchy demonstration video might be cool in the future? 🤔 
View modified readme [here](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/blob/daan/cleanup-readme/README.md)
=> Integrate more of the README.md into the sphinx site

hardware_integration/include/isobus/hardware_integration/can_hardware_interface.hpp, hardware_integration/include/isobus/hardware_integration/toucan_vscp_canal.hpp, hardware_integration/src/can_hardware_interface.cpp, hardware_integration/src/toucan_vscp_canal.cpp
* Added a way to get the current TouCAN serial number which is being used to connect the plugin to the hardware.
* Added a way to get the frame handler assigned to a hardware channel, which is useful in the VT for knowing which driver is in-use at any given time.
=> Minor enhancements to TouCAN and Hardware Interface

isobus/include/isobus/isobus/isobus_virtual_terminal_objects.hpp, isobus/src/isobus_virtual_terminal_objects.cpp, test/vt_object_tests.cpp
- Fixed an issue where change child position command packets inside macros could have been be truncated due to us assuming command packets would be 8 bytes. Now we allow arbitrary length. Actual handling of the lengths will be enforced by the [deserializer](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/blob/8b570184d4b146b56378ac03efce37e980ce9b33/isobus/src/isobus_virtual_terminal_server_managed_working_set.cpp#L2895C1-L2895C12).
(partially cherry picked from commit 798251171724c456ee74840f3dd9872832132d04)
=> Allow macro object command packets to be > 8 bytes

isobus/include/isobus/isobus/isobus_virtual_terminal_client.hpp, isobus/src/isobus_virtual_terminal_client.cpp
=> [VT]: Add handling of unsupported VT function

isobus/CMakeLists.txt, isobus/include/isobus/isobus/isobus_preferred_addresses.hpp
This was inspired by a comment on #407 and adds a reference for standard preferred control function addresses. This can be used as a reference for developers looking to assign a control function's preferred SA if they use a "well-known" standard function code.
As usual, users should not expect that the preferred address will be used if their NAME fails to arbitrate against another NAME on the bus that also wants that address. In those cases the stack will automatically select an appropriate address in the self configurable range if the NAME allows arbitrary address capabilities.
This information was directly sourced from the publically available ISO11783-11 database [here](https://www.isobus.net/isobus/attachments/isoExport_xlsx.zip). Since the change is header-only, no tests were …
=> [Core]: Add a reference for ISO and SAE preferred addresses

isobus/src/can_extended_transport_protocol.cpp
This change limits the ETP CTS to be only as many frames as are required to complete a session when receiving an ETP session. This change was required because in #418 I was seeing a situation where a control function was aborting our ETP Rx session because we CTS'd too many packets with the ISO 11783-3 reason "ECTS requested packets exceeds message size" as described in ISO11783-3 Table 9.
Fixes #418 
I used the TC server branch and the same control function to recreate the failing transfer, and it was successful.
Also, validated unit tests continued to pass.
=> [ETP]: Fixed issues where we could CTS too many packets

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/reinstall-cmake.sh
Add's a MS dev container for ubuntu 22.04 - gcc version 11.3.0-1ubuntu1~22.04.1 
Tested on Ubuntu 23.10 desktop, 
`Docker version 24.0.7, build afdd53b`, 
vscode 1.85.2, 
Dev containers version `2023-12-09, 06:02:20`
Ran build as per [CONTRIBUTING.md](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/blob/main/CONTRIBUTING.md#setting-up-a-development-environment-with-gui) without examples.
Added can-utils. Ran the `./scripts/setup_vcan.sh` on the host. Opened two teminal tty's inside vscode, worked sending and seeing message on candump.
=> Add vscode dev container

isobus/include/isobus/isobus/can_message.hpp, isobus/include/isobus/isobus/can_network_manager.hpp, isobus/include/isobus/isobus/nmea2000_fast_packet_protocol.hpp, isobus/src/can_extended_transport_protocol.cpp, isobus/src/can_message.cpp, isobus/src/can_network_manager.cpp, isobus/src/can_transport_protocol.cpp, isobus/src/nmea2000_fast_packet_protocol.cpp, test/cf_functionalities_tests.cpp, test/core_network_management_tests.cpp, test/diagnostic_protocol_tests.cpp, test/guidance_tests.cpp, test/helpers/control_function_helpers.cpp, test/helpers/messaging_helpers.cpp, test/helpers/messaging_helpers.hpp, test/isb_tests.cpp, test/language_command_interface_tests.cpp, test/maintain_power_tests.cpp, test/nmea2000_message_tests.cpp, test/speed_distance_message_tests.cpp, test/tc_client_tests.cpp, test/transport_protocol_tests.cpp, test/vt_client_tests.cpp
This should make it a bit more self-explanatory what the message needs to be functional, instead of needing to know which loosely-required functions you have to call before you get a functional message. Also did a few cleanups of the CANNetworkManager where older things were still present or unclear
Ran the virtual terminal examples to ensure core communication is still correct
=> [Core]: Require complete message representation at construction time

isobus/CMakeLists.txt, isobus/include/isobus/isobus/isobus_device_descriptor_object_pool.hpp, isobus/include/isobus/isobus/isobus_device_descriptor_object_pool_helpers.hpp, isobus/include/isobus/isobus/isobus_task_controller_client_objects.hpp, isobus/src/isobus_device_descriptor_object_pool.cpp, isobus/src/isobus_device_descriptor_object_pool_helpers.cpp, isobus/src/isobus_task_controller_client_objects.cpp, test/tc_server_tests.cpp
Added a helper to easily get implement geometry from a DDOP, which would be nice to have in a TC server.
This currently provides a static function `get_implement_geometry` which returns a vector of `Boom`s. Each boom then contains descriptions of that boom's geometry like this:
- Booms
- Sub Booms (if applicable)
- Sections
* X Offset
* Y Offset
* Z Offset
* Width
* X Offset
* Y Offset
* Z Offset
- Sections (if applicable)
* X Offset
* Y Offset
* Z Offset
* Width
* X Offset
* Y Offset
* Z Offset
Each value itself contains metadata so the user knows if the value is settable or not, and a way to check if the value is known or not (based on it being in a property versus being in a DPD for example).
You can check if values were provided by doing things like `if (booms.at(0).xOffset_mm)` for …
=> [TC]: Add a helper for getting implement geometry from a DDOP

isobus/include/isobus/isobus/can_NAME.hpp
- Added enums that define IGs and device classes/vehicle systems.
Besides being a nice reference to have, ~~I was considering using the device class to describe an implement type in the DDOP helper class I am working on. Such as "Sprayer", "Seeder" etc.~~ Edit: Or maybe not, since some values are used multiple times between different IGs. So I guess it's just a nice reference to have at this point.
This is a header only additive change, so assuming the unit tests compile in the GitHub actions, that should be sufficient.
=> [Core]: Add references for Industry Group and Device Class

hardware_integration/include/isobus/hardware_integration/mcp2515_can_interface.hpp, hardware_integration/src/mcp2515_can_interface.cpp, isobus/include/isobus/isobus/can_control_function.hpp, isobus/include/isobus/isobus/can_network_manager.hpp, isobus/include/isobus/isobus/can_parameter_group_number_request_protocol.hpp, isobus/include/isobus/isobus/can_stack_logger.hpp, isobus/include/isobus/isobus/isobus_functionalities.hpp, isobus/include/isobus/isobus/isobus_task_controller_client.hpp, isobus/include/isobus/isobus/isobus_virtual_terminal_client.hpp, isobus/include/isobus/isobus/nmea2000_fast_packet_protocol.hpp, isobus/src/can_control_function.cpp, isobus/src/can_network_manager.cpp, isobus/src/can_parameter_group_number_request_protocol.cpp, isobus/src/can_partnered_control_function.cpp, isobus/src/can_stack_logger.cpp, isobus/src/isobus_functionalities.cpp, isobus/src/isobus_task_controller_client.cpp, isobus/src/isobus_virtual_terminal_client.cpp, isobus/src/nmea2000_fast_packet_protocol.cpp, utility/include/isobus/utility/thread_synchronization.hpp
Removed #if and #endif directives in favor of single line macro for the lock guards
Also added some missing directives around <thread> includes
Made sure that code can still be compiled and ran the unit tests. Also self-reviewed the changes to make sure there are no copy-paste mistakes.
=> Refactor lock guards to use single line macro

examples/seeder_example/seeder.cpp, examples/task_controller_client/main.cpp
Changed examples that use TC clients to lock onto TCs with: 
* Device Class 0
* Industry Group 2
* Function Instance 0
* Function 130
Previously these only filtered on function code, which is not enough to positively identify a TC. This should resolve issues some people see when their bus has CFs with overlapping function codes.
Ran the modified seeder example on a real bus with TC, and it connected properly.
=> [Examples]: Changed examples that use TC client to have a more specific NAME filter

sphinx/source/Tutorials/The ISOBUS Hello World.rst
Fixes #432 
Fixes missing `isobus::Utility` target link library and some other updates.
=> [Docs] module import fix and inconsistencies hello-world tutorial

sphinx/source/Tutorials/The ISOBUS Hello World.rst
This is just a quick fix for a dead link in the ISOBUS Hello world docs.
=> [Docs]: Fix a dead link in ISOBUS hello world docs

examples/pgn_requests/main.cpp, isobus/include/isobus/isobus/can_callbacks.hpp, isobus/src/can_parameter_group_number_request_protocol.cpp
This adds the destination control function to callbacks the user gets when they have registered for requests for repetition rate.
Without this, how would the user know what internal control function to send the PGN from if they have more than one?
Ran PGN request example.
Further testing upcoming when I finish adding ISOBUS heartbeat in [this other branch](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/compare/main...adrian/heartbeat).
=> [Core]: Add destination control function to requests for repetition rate

isobus/include/isobus/isobus/can_internal_control_function.hpp, isobus/src/can_address_claim_state_machine.cpp, isobus/src/can_internal_control_function.cpp, test/address_claim_tests.cpp
This changes internal control functions and the address claim state machine to allow no preferred address or the null address (0xFE) as preferred. If no preferred address (or null) is provided, and the NAME allows for arbitrary addressing, we'll just find an address in the arbitrary address range for the user. If the user provides no address, and a NAME which doesn't support arbitration, we'll assert to tell them they made an error.
Also, clamped the range we were using for the arbitrary address range to max out at 235, where it was previously 247.
Closes #439 
Updated unit test to use the new functionality and verified an address was claimed using debugger.
=> [Core]: Made preferred address optional

examples/seeder_example/seeder.cpp, isobus/CMakeLists.txt, isobus/include/isobus/isobus/can_general_parameter_group_numbers.hpp, isobus/include/isobus/isobus/can_network_manager.hpp, isobus/include/isobus/isobus/isobus_heartbeat.hpp, isobus/src/can_network_manager.cpp, isobus/src/isobus_heartbeat.cpp, sphinx/source/api/implement messages/guidance.rst, sphinx/source/api/implement messages/heartbeat.rst, sphinx/source/api/implement messages/index.rst, sphinx/source/api/implement messages/maintain power.rst, sphinx/source/api/implement messages/shortcut.rst, sphinx/source/api/implement messages/speed distance.rst, sphinx/source/api/index.rst, test/CMakeLists.txt, test/diagnostic_protocol_tests.cpp, test/heartbeat_tests.cpp
Added an interface which manages sending and receiving the ISOBUS heartbeat.
The heartbeat message is used to determine the integrity of the communication of messages and parameters being transmitted by a control function. There may be multiple instances of the heartbeat message on the network, and CFs are required transmit the message on request. As long as the heartbeat message is transmitted at the regular time interval and the sequence number increases through the valid range, then the heartbeat message indicates that the data source CF is operational and provides correct data in all its messages.
This interface is enabled by default, but can be disabled if you want to stop your heartbeat(s) or don't care about the safety-critical path of the machine. …
=> [TECU]: Add ISOBUS Heartbeat Message

isobus/include/isobus/isobus/isobus_device_descriptor_object_pool_helpers.hpp, isobus/include/isobus/isobus/isobus_standard_data_description_indices.hpp, isobus/src/isobus_device_descriptor_object_pool_helpers.cpp, test/tc_server_tests.cpp
This provides a way to get rate/product information from a DDOP. Generally it considers any `Bin` to be the root of a product, which seems to be fairly standard.
This is intended to be used in a TC server to quickly learn about what products the implement might have.
The information provided includes data about:
- Default rate
- Setpoint rate
- Actual rate
- Minimum rate
- Maximum rate
Expanded TC server unit tests to include parsing for product information.
=> [TC]: Add product abstraction to DDOP helper

isobus/src/can_network_manager.cpp
This PR fixes a log statement that previously printed fields of the partnered control function that where not populated with the correct data yet.
=> [Core]: Fix log statement for partner claiming address

CMakeLists.txt
This PR: 
- Adds a clear option in CMake for disabling threading
- Stops searching for threads from the root if threading is disabled
- Tested compilation with CAN_STACK_DISABLE_THREADS of just isobus.lib doesn't link pthreads, and makes no "Threads found" output
=> [CMAKE]: When threading is disabled, don't attempt to find threads

examples/seeder_example/vt_application.cpp
With this PR we make sure that we don't miss an update by always letting it poke our "process_new_speed" function.
This fixes a bug where the speed doesn't get updated when re-entering the main screen and speed isn't changing anymore.
Ran the seeder-example and made sure that this bug disappeared
=> [Examples] Fix speed sometimes not updating in seeder example

isobus/src/isobus_virtual_terminal_client.cpp
When testing I found that the seeder example gave a deadlock when trying to spam the settings soft-key immediately after startup. This PR resolves that issue.
Might be a fix for #449, further testing needed
=> [VT]: Fix missing lock guard and deadlock in iterator

isobus/include/isobus/isobus/isobus_language_command_interface.hpp, isobus/include/isobus/isobus/isobus_task_controller_client.hpp, isobus/src/isobus_language_command_interface.cpp, isobus/src/isobus_task_controller_client.cpp, test/language_command_interface_tests.cpp, test/tc_client_tests.cpp
This change alters how we deal with the language command PGN in the TC client to be more reliable and more tolerant of TCs which don't fully comply with version 4 of the standard when they claim they're version 4.
- Allow the TC client to fall back to other language sources as needed.
- Fixed a condition where the TC client would become stuck while waiting for a language response if a response never arrived. 
- Added a getter to the language command interface to allow retrieving the assigned partner CF. 
- Prevent a crash in the language command interface which could occur if you send the command with some fields left unconfigured.
- Removed TC client's dependency on the VT client.
~~This is pretty challenging to test in a unit test without a large amount of boiler plate code, so it has …
=> [TC]: Add options for falling back to other language data sources when TC doesn't respond

isobus/include/isobus/isobus/can_control_function.hpp
This fixes a missing include in can_control_function.hpp as discussed in #451 
Compiled a version of the VT example where `string` wasn't included prior to including the `can_control_function.hpp` file.
=> [Core]: Fixed a missing string include

isobus/CMakeLists.txt, isobus/include/isobus/isobus/isobus_data_dictionary.hpp, isobus/src/isobus_data_dictionary.cpp
This allows you to disable the ISOBUS data dictionary if you want to save a bunch of ROM/RAM space in your binary.
This was very helpful on the STM32 platform I'm testing on.
Unit tests which use the data dictionary interface still compile with the database disabled.
=> [TC]: Allow disabling the data dictionary to save on binary/RAM size

examples/seeder_example/section_control_implement_sim.cpp, examples/seeder_example/section_control_implement_sim.hpp, examples/task_controller_client/section_control_implement_sim.cpp, examples/task_controller_client/section_control_implement_sim.hpp, isobus/include/isobus/isobus/isobus_task_controller_client.hpp, isobus/src/isobus_task_controller_client.cpp, test/tc_client_tests.cpp
- Fixed casting issues when determining the TC client process variable values. Some incorrect casts may have been truncating the value, especially for measurement trigger commands.
- Changed TC client process variable value to be a signed value, as it should be according to the definition in ISO 11783-10 B.3.4
Added a unit test for negative process variable values, and ensured other TC client tests still passed.
=> [TC]: Changed TC client process variable value to be interpreted as signed

.github/workflows/build.yml, .github/workflows/linting.yml, .github/workflows/pio.yml
Updates some GitHub actions to fix a deprecation warning for node.js 16.
The updated actions will have run with this PR. If they worked, it should be OK to update.
=> [CI]: Update some GitHub actions to fix deprecation warnings

isobus/src/can_internal_control_function.cpp
This just adds the cassert header to can_internal_control_function source file. We use the assert macro in there, but it wasn't included.
This had been causing a compilation issue for me in another branch, which is interesting since the CI is passing, but adding this line allows it to compile.
=> [Core]: Add missing cassert to internal control function source file

isobus/src/can_extended_transport_protocol.cpp
Adds the "successful" parameter to the logging output for when an end of message acknowledgment is received. Can be useful when debugging weird looking behavior after an ETP tx session.
=> [ETP]: Add small addition to logging in eom ack

isobus/src/isobus_virtual_terminal_client.cpp
Fixes a small printf formatting mistake where it took in an uint64 instead of the passed in uint8 for the function code, which gave weird numbers in the log on an ESP32.
=> [VT]: Fix logging output of unsupported functions

isobus/src/isobus_virtual_terminal_client_state_tracker.cpp
Fixed what appears to be a copy-paste error in VirtualTerminalClientStateTracker which would result in a double free on occasion when exiting a consuming application.
Tested using the VT example on Ubuntu 22.04 with a PCAN device and socketCAN.
Before:
After:
=> [VT]: Fix a double free in VirtualTerminalClientStateTracker

hardware_integration/CMakeLists.txt, hardware_integration/include/isobus/hardware_integration/vector_asc_logger.hpp, hardware_integration/src/vector_asc_logger.cpp, isobus/src/isobus_time_date_interface.cpp
This adds an interface to the hardware layer to natively create vector ascii log files, to eliminate the need for something like candump to log what your program is doing if you want. For devices like the PCAN probe on Windows, this eliminates the need for a second CAN device to log the bus. This is basically copied from AgIsoVirtualTerminal, but with Juce removed.
Also removed one unused parameter in the time/date interface.
It's best to instantiate this before you call "start" on the hardware layer so you get all the messages.
Added a `VectorASCLogger` to the VT example, ran it for a while, stopped it, then compared with a file created by Peak's trc converter tool set to "version 17" of the file specification.
=> [HW]: Add native logger for vector ascii CAN traces

hardware_integration/src/can_hardware_interface.cpp
Fixed an issue where we weren't checking the return value of the push into our Tx queue in our hardware interface. This could have caused some frames to be accidentally dropped.
Recreated the issue discussed [here](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/issues/476#issuecomment-2174568075) with AgIsoVirtualTerminal with the number of frames per DOP set to 255, and witnessed frames being dropped.
Added this check, and now object pool properly uploads!
This may fix #476
=> [HW]: Fixed possibly dropping messages on Tx when Tx buffer is full

isobus/include/isobus/isobus/isobus_speed_distance_messages.hpp, test/speed_distance_message_tests.cpp
Fixed incorrect values interpreted and sent for SPNs 1861, 4309, 1864, and 4312.
Fixes #491 
Updated unit tests to cover this change, 100% covered.
=> Swap Forward and Reverse in MachineDirection enumeration

isobus/src/isobus_virtual_terminal_client.cpp
Fixed some missing object lengths in the VT client autoscaling logic.
Fixes #492 
Tested by consumer in #492
=> Fix autoscaling object pool when Auxiliary objects present in object pool

isobus/src/isobus_virtual_terminal_objects.cpp
ISO 11783-6 states that when picture graphics have extra data bytes they should be ignored.
We were apparently not doing that, treating that as an error condition instead.
Now we will properly deal with that requirement, which is worded as `If the data are longer than expected after all of the rows and columns of pixels have been defined, then the VT shall ignore all extra data bytes`
Fixes [this issue in the VT](https://github.com/Open-Agriculture/AgIsoVirtualTerminal/issues/25)
Tested using a hand-crafted test application using object pools extracted from [this issue](https://github.com/Open-Agriculture/AgIsoVirtualTerminal/issues/25).
Previously parsing the IOP would fail, and now it does not.
=> Tolerate excess bytes in picture graphic raw data when deserializing IOPs

isobus/include/isobus/isobus/isobus_task_controller_server.hpp, isobus/src/isobus_task_controller_server.cpp
It looks like version reported by the client can be quite useful for example for proper parsing of received DDOP before it will be activated. Otherwise version 4 is used for parsing by default which can be wrong assumption.
So far while DDOP is parsing some default (4) version is used. There is no direct possibility to check which version received binary DDOP stream is actually coded. On the other hand client reports its version in advanced so it can be stored and use later on for proper DDOP parsing.
This PR contains adding new public field to class `ActiveClient` which stores `reportedVersion` for later use.
Own `TaskController` implemented on ESP32 connected to real Gaspardo corn seeder ISOBUS controller uint.
=> [TC]: store reported by client version to use it later for DDOP parsing

isobus/src/isobus_virtual_terminal_working_set_base.cpp
This changes the deserializer for VT object pools to allow UTF-16 strings. Display of the string is the responsibility of the consuming application so there's no reason to deny a UTF-16 string here.
Once this is merged in I can finish the [associated issue](https://github.com/Open-Agriculture/AgIsoVirtualTerminal/issues/27) in AgIsoVirtualTerminal.
Tested by deserializing an object pool with a UTF-16 string in it which was provided by a community member in our Telegram group.
=> [WS]: Allow UTF-16 string variables to be deserialized

hardware_integration/CMakeLists.txt, hardware_integration/src/sys_tec_windows_plugin.cpp
Related to [this issue](https://github.com/Open-Agriculture/AgIsoVirtualTerminal/issues/34) on AgIsoVirtualTerminal.
Fixed some compilation issues which happen on Windows when compiling with MinGW. Specifically, the innomaker driver is not compatible with it seemingly due to how it was compiled, and also `std::this_thread` was not getting defined in the sys_tec plugin.
=> [HW]: Fix some issues when compiling with MinGW

isobus/src/isobus_virtual_terminal_server.cpp
Added Output string objects to the objects capable of receiving Change size commands.
Also alphabetized the switch cases handling this.
Loaded IOP containing a macro having Change size commands included for Output Strings
=> Handle Change Size commands for OutputString objects too

isobus/src/isobus_virtual_terminal_objects.cpp
When clicking on a main screen button in AgIsoVT in a Kverneland seeder implement  the following error thrown:
```
[VT Server]: Client 133 change child location failed because the target object with ID 381 isn't applicable
```
and the image from the button started to move downright in 45°slope.
By peeking the code I found a missing return value setting in the VTObject::offset_all_children_with_id
Built AgIsoVT with this change and the button remained clickable and no error output had been shown.
=> Fix return value of VTObject::offset_all_children_with_id

isobus/src/isobus_virtual_terminal_objects.cpp
While testing some implements with AgIsoVT I came across invisible texts on white background.
They turned out to be lightgray on an Amatron 4:
They used 252 color code for this OutputNumber which is proprietary, and so far all proprietary were treated as white.
I looked up Jetter IsoDesigner (as the IOP in question was designed with it), and they color palette is the following:
Built AgIsoVT with this change and the texts got visible
=> Use proprietary colors used by Jetter IsoDesigner instead of just white

examples/transport_layer/main.cpp, hardware_integration/CMakeLists.txt, hardware_integration/include/isobus/hardware_integration/available_can_drivers.hpp, hardware_integration/include/isobus/hardware_integration/ntcan_plugin.hpp, hardware_integration/src/ntcan_plugin.cpp, sphinx/source/api/hardware/index.rst
Continued #198
I will create another PR in the coming days that adds an example on how to bridge two hardware plugins together. This allows one to use a virtual bus, while connecting it to (multiple) physical busses as well.
I have tested it using their virtual can bus and everything is functioning as it should.
=> NTCAN hardware plugin

.github/workflows/build.yml
My hope is that this fixes new errors we are seeing in the pipeline with gcovr parsing the output from gcov.
At some point the version of `gcov` being used in our Ubuntu builds must have changed or something.
Removing the hard pin to 5.0 looks like it installs version 8.2, which seems to resolve the errors.
=> [CI]: Allow for newer gcovr in builds

hardware_integration/include/isobus/hardware_integration/vector_asc_logger.hpp
Motivation. Compilation error while building without threads.
Root cause. `can_hardware_interface.hpp` uses `std::time_t` without including `ctime`
Fix. Added missing header.
Reproduction path and error log before the change: 
```
$ cmake -S . -B build -DCAN_STACK_DISABLE_THREADS=true
<--- snip --->
$ cmake --build build
<--- snip --->
[ 96%] Building CXX object hardware_integration/CMakeFiles/HardwareIntegration.dir/src/vector_asc_logger.cpp.o
In file included from /home/stan/githome/agiso/AgIsoStack-plus-plus-fork/hardware_integration/src/vector_asc_logger.cpp:6:
/home/stan/githome/agiso/AgIsoStack-plus-plus-fork/hardware_integration/include/isobus/hardware_integration/vector_asc_logger.hpp:46:60: error: ‘time_t’ in namespace ‘std’ does not name a type; did you mean ‘time_put’?
46 | …
```
=> [HW]: Add missing header

isobus/src/isobus_virtual_terminal_server.cpp
There were some object types where the change size command was not handled.
A Müller implement had a OutputLinearBarGraph which got resized by button press resulting error output and invisible widget. 
If I fixed it I added the other resizeable objects too.
=> Support of Change Size command to all object types where it should be supported

isobus/include/isobus/isobus/isobus_virtual_terminal_server.hpp, isobus/src/isobus_virtual_terminal_server.cpp
Rename get_soft_key_descriptor_y_pixel_width to get_soft_key_descriptor_y_pixel_height
I worked on the softkey dimensions in AgIsoVirtualTerminal#65 and found this misnamed member what I renamed for the shake of better readability.
=> Rename get_soft_key_descriptor_y_pixel_width 

.github/workflows/build.yml, .github/workflows/pio.yml
This apparently is a bug somewhere in the eco system, see https://github.com/gcovr/gcovr/issues/583#issuecomment-1340762818. It sometimes causes the pipeline to fail (e.g. [this one](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/actions/runs/12658787226/attempts/1)).
Furthermore I tried to update the rest to the [template](https://github.com/sonarsource-cfamily-examples/linux-cmake-gcovr-gh-actions-sc/blob/main/.github/workflows/build.yml) action as much as possible. They had made some changes.
=> [CI]: Silence gcovr complaining about negative hit errors

examples/seeder_example/vt_application.cpp, isobus/include/isobus/isobus/isobus_virtual_terminal_client_state_tracker.hpp, isobus/src/isobus_virtual_terminal_client.cpp, isobus/src/isobus_virtual_terminal_client_state_tracker.cpp, isobus/src/isobus_virtual_terminal_client_update_helper.cpp, utility/include/isobus/utility/platform_endianness.hpp, utility/src/platform_endianness.cpp
Resolves the comment open in #482. This saves duplication, as the standard is treating the float identical to the uint32_t after conversion.
=> [VT-helper]: Direct conversion of float to byte representation

examples/virtual_terminal/esp32_platformio_object_pool/platformio.ini, examples/virtual_terminal/esp32_platformio_object_pool/src/main.cpp, sphinx/source/Tutorials/ESP32 PlatformIO.rst
This PR fixes the length of the object pool being one off. It also clarifies how to embed files, like an object pool, with ESP32 and PlatformIO in the tutorial. And adds default environment for `platformio.ini` to stop building CI by default
Fixes #496, #359
=> Fix incorrect length of object pool in ESP32 example

isobus/include/isobus/isobus/isobus_virtual_terminal_working_set_base.hpp, isobus/src/isobus_virtual_terminal_working_set_base.cpp
Fixes Open-Agriculture/AgIsoVirtualTerminal#69
The ISO 11783-6 does mention that the replacing of the objects is supported, but does not constrain on the already loaded object type.
A Müller Implement loads fine with this change with AgIsoVT. Previously the IOP load failed.
=> Allow replacing objects during IOP load even if existing object type differ

isobus/include/isobus/isobus/isobus_virtual_terminal_objects.hpp, isobus/src/isobus_virtual_terminal_objects.cpp
Removed duplicate codes to support Open-Agriculture/AgIsoVirtualTerminal#55
Loaded Kverneland implements in AgIsoVT
=> Remove duplicated code

examples/seeder_example/vt_application.cpp, isobus/include/isobus/isobus/isobus_virtual_terminal_client_state_tracker.hpp, isobus/include/isobus/isobus/isobus_virtual_terminal_client_update_helper.hpp, isobus/src/isobus_virtual_terminal_client.cpp, isobus/src/isobus_virtual_terminal_client_state_tracker.cpp, isobus/src/isobus_virtual_terminal_client_update_helper.cpp, utility/include/isobus/utility/platform_endianness.hpp, utility/src/platform_endianness.cpp
This lets you use the VT state helper to deal with float attributes. Previously, float values were probably not handled correctly.
I was seeing that there were warnings in the seeder example about this:
=> [VT]: Add a way to track VT float attributes

isobus/include/isobus/isobus/isobus_device_descriptor_object_pool.hpp, isobus/src/isobus_device_descriptor_object_pool.cpp
This PR allows you to extend an already existing populated DDOP object with more binary data. This is especially useful if the DDOP is transferred in multiple trips to the TC.
=> [TC]: Extending DDOP with binary object pool

hardware_integration/include/isobus/hardware_integration/can_hardware_plugin.hpp
In order to be able to use classes such as `isobus::CANHardwarePlugin` polymophically [C++ requires][cpp11_expr_del] a public `virtual` destructor in the base class, otherwise the behaviour of the delete expression via pointer-to-base is undefined.
This was picked up by my client's linter.
For reference, this check is enabled in [Sonar][sonar_rspec_1235] but it seems to miss this file somehow.
Fixes # (issue)
No issue found in tracker.
Patch applied internally and linting no longer reportes this error.
[cpp11_expr_del]: https://timsong-cpp.github.io/cppwp/n3337/expr.delete#3
[sonar_rspec_1235]: https://rules.sonarsource.com/cpp/RSPEC-1235/
=> Use public virtual destructor in isobus::CANHardwarePlugin

isobus/include/isobus/isobus/isobus_virtual_terminal_client.hpp, isobus/src/isobus_virtual_terminal_client.cpp
Command and macro messages send to the VT need to be queued if there is a response pending for the previous command. Currently there is for some of these messages a check in place that checks if the to-be-queued message overwrites the result of any of the previously queued commands.
This PR completed that feature for (almost) every command.
=> [VT-client]: refine replacement of already queued commands

CMakeLists.txt, hardware_integration/CMakeLists.txt
I have consulted the [Espressif IDF Build System](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/build-system.html#build-system) documentation while creating a minimalist [AgIsoStack-on-ESP32](https://github.com/j-c-cook/AgIsoStack-on-ESP32) example project. The project successfully links to the TWAI hardware files, flashes on an ESP32 development board and initializes the `canDriver`. 
See the minimalist [AgIsoStack-on-ESP32](https://github.com/j-c-cook/AgIsoStack-on-ESP32) repository.
=> Modifications to build cleanly for ESP32 using the ESP IDF component style structure

isobus/src/isobus_task_controller_server.cpp
Added the call to the timeout function to resolve the issue
Ran the seeder example and let it timeout. The `on_client_timeout ` function got now called.
=> [TC]: Server not calling on_client_timeout function

isobus/include/isobus/isobus/can_identifier.hpp, isobus/src/can_identifier.cpp
=> fix(can_identifier): fix typo

CMakeLists.txt
While compiling the project for the ESP32 I was getting two `-Wpedantic` warnings from ESP libraries (assert and twai). The code is compiling and working fine, but producing build warnings. The idea of this PR is to get rid of them since, as far as I understood, I can't add the compile option only for this library as the espressif CMake fork for won't allow me: [source](https://stackoverflow.com/questions/79035496/strict-compilation-werror-wpedantic-only-for-my-project-files-on-esp-idf)
The project was compiled both with the ESP_PLATFORM flag enabled and disabled to check the warnings during the build
Using the [AgIsoStack-on-ESP32](https://github.com/j-c-cook/AgIsoStack-on-ESP32) repository to test the compile logs, we can see that the `-Wpedantic` warnings were gone.
=> [CMAKE]: Compile Target Options for ESP32 Platform

isobus/include/isobus/isobus/isobus_virtual_terminal_objects.hpp
Made the Button::set_options virtual
Necessary for: Open-Agriculture/AgIsoVirtualTerminal#84
Built AgIsoVT with a version which it relies on this change.
=> Make button setoptions virtual

hardware_integration/include/isobus/hardware_integration/can_hardware_interface.hpp, hardware_integration/src/can_hardware_interface.cpp, isobus/include/isobus/isobus/can_control_function.hpp, isobus/include/isobus/isobus/can_network_manager.hpp, isobus/src/can_network_manager.cpp
Fixes the warnings in the TSAN output in this [issue](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/issues/544). It reports multiple data races.
By applying the changes in this PR, we make sure that all operations are atomic, or guarded by a mutex.
Fixes #544
This has been tested by running the `PGNRequestExampleTarget` and making sure all TSAN warnings were gone.
Furthermore, I have looked into the newly added mutex; it shouldn't be possible to reach a deadlock
=> [HW]: Fix data race condition on started variable

isobus/include/isobus/isobus/can_network_manager.hpp, isobus/src/can_network_manager.cpp, test/address_claim_tests.cpp
This could be used to check for the continued existence of a control function at the network level. 
This should be used sparingly, but I can see it being desirable.
It is not to be used as a normal part of the address claim process, as normal address claiming is handled elsewhere.
RE: #542 
Added unit test. This code was literally copied from the internal control function, so it should work the same.
=> [NM]: Added a method for forcing a request of the address claim PGN

hardware_integration/src/vector_asc_logger.cpp, isobus/src/isobus_time_date_interface.cpp, isobus/src/isobus_virtual_terminal_server.cpp, isobus/src/isobus_virtual_terminal_server_managed_working_set.cpp, isobus/src/isobus_virtual_terminal_working_set_base.cpp
The isobus module has a DISABLE_CAN_STACK_LOGGER option.
When this option is set the build failed because the CANStackLogger methods used across the stack but not defined. 
Added dummy methods to CANStackLogger to overcome this error.
```bash
cmake .. -DDISABLE_CAN_STACK_LOGGER=ON
make
#successful build
```
=> Fix building with CAN logger disabled

CONTRIBUTING.md, docs/pre-commit-hook.sh
Added pre commit hook to perform the following actions:
* Run inplace clang-format on each committed *.cpp and *.hpp file
* Run inplace cmake-format on each committed CMakeLists.txt file
* Check all committed *.cpp and *.hpp file for containing calls for CANStackLogger and prevents commit if found
Tried to commit cpp files containing CANStackLogger::warn calls and the commit was prevented
Tried to commit ill-formatted file and the formatting got applied
=> Add pre-commit hook template

isobus/include/isobus/isobus/can_control_function.hpp
This fixes a compilation issue on Ubuntu 2204 when compiling with threads disabled.
Fixes #565
Compiled in a Ubuntu 22.04 VM
=> [Core]: Changed control function address atomic type

isobus/src/isobus_virtual_terminal_server_managed_working_set.cpp
This was causing an assert in the VT when iopSize was exactly zero.
This fixes that by returning 0% when the IOP size is zero.
Verified that the assert stopped happening when uploading an object pool using a debugger.
=> Fixed a divide by zero issue when calculating IOP load percentage

isobus/src/can_network_manager.cpp
Condition for NAME contention should be opposite. We won when our NAME is smaller than their NAME. 
In the code `claimedNAME` is their NAME. So, to allow us to win it should be larger than our NAME.
Fixes #564
Relates to #567
Python script based on j1939 library with manually changed NAME.
=> Fix NAME contention condition

isobus/include/isobus/isobus/isobus_virtual_terminal_server.hpp, isobus/src/isobus_virtual_terminal_server.cpp
Added response sending to the Control Audio Signal and Set Audio Volume commands
I came across a VT implement (Väderstad Tempo) which stuck with an alarm mask if no response is sent to the Control Audio Signal command:
Build AgIsoVT wit this change and the Tempo VT implement loaded just fine:
The Set Audio Volume response is untested.
=> Send audio responses

isobus/src/can_network_manager.cpp
When multiple Partnered Control Functions (PCFs) register callbacks for the same Parameter Group Number (PGN), the callbacks were being triggered for any message with a matching PGN, regardless of the source control function. This caused callbacks to execute for messages from unrelated control functions.
The fix adds source control function validation in the message routing by adding a check `(partner == messageSource)` in the PCF message processing logic. This ensures callbacks are only triggered when both the PGN matches and the message comes from the specific PCF that registered the callback.
This change:
- Prevents callbacks from being triggered by unrelated control functions
- Eliminates the need for manual source control function checking in callbacks
- Makes callback behavior more …
=> fix: Ensure PCF callbacks only trigger for matching source control functions

isobus/src/can_internal_control_function.cpp, isobus/src/can_network_manager.cpp
- Fixed an issue where ICFs could send too many address claims if a destination specific request was made.
- This change makes ICFs only re-claim in response to a request to do so when the destination of the request was the ICFs address or the global address. Previously they would claim for any request to any address which was incorrect.
- Don't use destination specific requests for address claim when determining online/offline CF states
- ISO 11783-5 permits destination specific PGN requests for the address claimed PGN, and in those cases we were treating it the same as a global request when determining if a CF went offline or not. This fixes that such that only global requests will run that logic.
Fixes #573 
Tested by simulating destination specific address claims and walking the code …
=> Fixed issues with PGN requests for the address claimed PGN sent to specific destination addresses

isobus/src/isobus_virtual_terminal_server.cpp
Removed extra variable passed to the debug logger function which does not have a placeholder in the string.
=> Fix change font attribute debug  message

isobus/src/can_network_manager.cpp, isobus/src/isobus_virtual_terminal_server.cpp
**Issue**
The `foundControlFunction` address was not being updated with `claimedAddress` prior to calling `process_control_function_state_change_callback`, therefore the address in the callback appeared as 0xfe. 
**Before**
```
AgIsoStack: [NM]: Partnered control function with name xxxxxxxxxxxxx has claimed address 213 on channel 1.
Device came online - Channel: 1 NAME: "xxxxxxxxxxxxx" Source Address: "0xfe" Identity: 2088747 Manufacturer: xxx Function: xxx
```
**After**
```
AgIsoStack: [NM]: Partnered control function with name xxxxxxxxxxxxx has claimed address 213 on channel 1.
Device came online - Channel: 1 NAME: "xxxxxxxxxxxxx" Source Address: "0xd5" Identity: 2088747 Manufacturer: xxx Function: xxx
```
=> Fix control function callback order of events to contain claimed address

isobus/include/isobus/isobus/can_internal_control_function.hpp, isobus/src/can_internal_control_function.cpp, test/address_claim_tests.cpp
ISO11783 defines the behavior that should happen when an internal control function actually cannot get an address, and although we correctly prevent sending application level messages in these cases, we were missing the transmission of the "cannot claim source address" message. This fixes this and corrects the non-compliant behavior.
Added unit test to validate this behavior where a very low ISO NAME claims every single address on the bus before we make an internal control function.
=> Add proper sending of cannot claim source address message

isobus/src/isobus_virtual_terminal_working_set_base.cpp
Added missing value set when parsing input strings
Build AgIsoVT, ran NX9 test implement and the following input strings now matching the NX9 VT:
NX9 (reference)
(old AgIsoVT behavior)
(Fixed AgIsoVT):
=> Set the value of the InputStrings from the parsed IOP

examples/seeder_example/section_control_implement_sim.cpp, examples/seeder_example/vt_application.cpp, isobus/src/isobus_task_controller_client.cpp
- Fixed possibly sending PDACKs with garbage data due to an order of operations issue with value command responses.
- Since our VT client reports version 4 as the default, change seeder example default DDOP version to 4. 
- Fix seeder example request for default process data being orphaned and using wrong DDI. 
- Fix seeder example orphaned total area DPD.
Tested/fixed using an ISOBUS task controller on a live bus. I found these while testing #486
=> [TC]: Fix incorrect PDACKs possibly sent by TC client

examples/seeder_example/main.cpp, examples/seeder_example/seeder.cpp, examples/seeder_example/seeder.hpp
I do VT testing with the SeederExample and I needed to change between CAN interfaces quite often.
To simplify these changes I have added handling for a single  command line option which is used as a CAN interface name.
For socketcan the interface name is used as a string.
For PCAN based interfaces the PCAN_USBBUS<n> is used with a numeric argument.
For Innomaker interfaces the argument as a number used for channel.
Opened multiple socketCAN interfaces with the help of command line arguments.
I have not been able to test PCAN on Windows/MacOS and Innomaker interfaces.
=> Add CAN interface command line option to the SeederExample

hardware_integration/src/can_hardware_interface.cpp, test/hardware_interface_tests.cpp
Updated `CANHardwareInterface::stop()` so the started flag is cleared regardless of threading mode, fixing the stuck “running” state when CAN_STACK_DISABLE_THREADS is defined. Added two hardware interface unit tests that reproduce the original failure in non-threading mode and confirm that the flag, channel unassignment, and restart workflow behave correctly after the fix.
Fixes #557 
```bash
mkdir build_no_threads
cd build_no_threads
cmake -DCAN_STACK_DISABLE_THREADS=ON -DBUILD_TESTING=ON ..
make
./test/unit_tests --gtest_filter="HARDWARE_INTERFACE_TESTS.StopSetsStartedFalseInNonThreadingMode"
```
=> Fix started flag behaviour #557

hardware_integration/include/isobus/hardware_integration/can_hardware_plugin.hpp, hardware_integration/include/isobus/hardware_integration/flex_can_t4_plugin.hpp, hardware_integration/include/isobus/hardware_integration/innomaker_usb2can_windows_plugin.hpp, hardware_integration/include/isobus/hardware_integration/mac_can_pcan_plugin.hpp, hardware_integration/include/isobus/hardware_integration/mcp2515_can_interface.hpp, hardware_integration/include/isobus/hardware_integration/ntcan_plugin.hpp, hardware_integration/include/isobus/hardware_integration/pcan_basic_windows_plugin.hpp, hardware_integration/include/isobus/hardware_integration/socket_can_interface.hpp, hardware_integration/include/isobus/hardware_integration/sys_tec_windows_plugin.hpp, hardware_integration/include/isobus/hardware_integration/toucan_vscp_canal.hpp, hardware_integration/include/isobus/hardware_integration/twai_plugin.hpp, hardware_integration/include/isobus/hardware_integration/virtual_can_plugin.hpp, hardware_integration/src/flex_can_t4_plugin.cpp, hardware_integration/src/innomaker_usb2can_windows_plugin.cpp, hardware_integration/src/mac_can_pcan_plugin.cpp, hardware_integration/src/mcp2515_can_interface.cpp, hardware_integration/src/ntcan_plugin.cpp, hardware_integration/src/pcan_basic_windows_plugin.cpp, hardware_integration/src/socket_can_interface.cpp, hardware_integration/src/sys_tec_windows_plugin.cpp, hardware_integration/src/toucan_vscp_canal.cpp, hardware_integration/src/twai_plugin.cpp, hardware_integration/src/virtual_can_plugin.cpp
I have added a get_name method to the CANHardwarePlugin (and to all derived implementations).
I have some plans to simplify/make nicer the CAN plugin selection in AgIsoVT and this would be required to it.
CI got it built
=> Add get_name method to the CANHardwarePlugin
