isobus/include/can_managed_message.hpp, isobus/include/can_protocol.hpp, isobus/include/can_transport_protocol.hpp, isobus/src/can_managed_message.cpp, isobus/src/can_network_manager.cpp, isobus/src/can_transport_protocol.cpp
Previously, only TP BAM Rx was really working.
Now, CM transmits are also working!
There may still be some lingering issues with when sessions need to be
cleaned up if they get aborted by the destination, but this is a big
step.
=> [TP]: Working CM Transport Protocol Tx Sessions

README.md
Updated readme with a better status, added some more CMake instructions
=> [Meta]: Update README with better status

isobus/include/isobus_virtual_terminal_client.hpp, isobus/src/can_NAME_filter.cpp, isobus/src/can_partnered_control_function.cpp
Fixed a couple comparison mismatches and one missing include that some compilers care about.
=> Clean up warnings and one error on some compilers

isobus/src/can_transport_protocol.cpp
Also cleaned up some magic numbers that correspond to the classic CAN packet length, and cleaned up one debug output that was log-spammy
=> [TP]: Added aborts for sequence number issues when receiving TP messages

.github/workflows/codeql-analysis.yml, isobus/src/can_extended_transport_protocol.cpp
Adding security scanning.
Not sure how this will work, so creating a PR to allow the workflow to run.
=> [Meta]: Add CodeQL scanning

isobus/src/can_transport_protocol.cpp
The stack was always trying to dereference the destination control function in the transport protocol transmit, even when it was `nullptr`. Also removed a spammy logger call that wasn't very helpful anyways.
=> [TP]: Fixed a crash that happened when sending a BAM message

README.md
Updated readme to reflect current state.
Marking ETP as complete, as I have now tested many payloads. Marking BAM Tx as complete, as I have now tested all message lengths. Adding DM2 to in-progress state.
Removed the "Important note" as the transport layer is much more mature now.
=> [Meta]: Update README

CMakeLists.txt, README.md
- Document how to run tests, solving #39 
Signed-off-by: Ryan Friedman <ryan_friedman@trimble.com>
=> [39] Add support for ctest to enable/disable testing

README.md, isobus/include/can_identifier.hpp, sphinx/README.md, sphinx/make.bat, sphinx/source/API Documentation.rst, sphinx/source/Concepts.rst, sphinx/source/FAQ.rst, sphinx/source/Installation.rst, sphinx/source/License.rst, sphinx/source/Releases.rst, sphinx/source/Tutorials.rst, sphinx/source/Tutorials/Adding a Destination.rst, sphinx/source/Tutorials/Receiving Messages.rst, sphinx/source/Tutorials/The ISOBUS Hello World.rst, sphinx/source/Tutorials/Transport Layer.rst, sphinx/source/conf.py, sphinx/source/index.rst
I've created a first draft of a tutorial website here: https://delgrossoengineering.com/isobus-tutorial/index.html
I am seeking feedback on it if anyone has some!
The tutorial site was written in reStructuredText and compiled with sphinx. See the README in the sphinx folder for info on how to compile it.
I've also started some testing in RHEL 9, so I've added a few instructions to the README for RHEL users.
=> Add Tutorial Website

.gitlab-ci.yml
Added this for anyone like me who also has a GitLab instance.
Now GitLab will also build and pack the code automatically if you're into that kind of thing.
=> [Meta]: Added a gitlab-ci file

isobus/include/isobus/isobus/can_NAME.hpp
Fix some weird Unicode characters in comments of can_NAME.hpp
=> [Meta]: Fix some comment unicode characters

CMakeLists.txt, README.md, examples/nmea2000/CMakeLists.txt, examples/nmea2000/main.cpp, isobus/CMakeLists.txt, isobus/include/isobus/isobus/can_NAME.hpp, isobus/include/isobus/isobus/can_network_manager.hpp, isobus/include/isobus/isobus/nmea2000_fast_packet_protocol.hpp, isobus/src/can_NAME.cpp, isobus/src/nmea2000_fast_packet_protocol.cpp
* Adds support for sending and receiving NMEA 2000 fast packet messages
* Adds a NMEA2K example program
=> [FP]: Add NMEA 2000 Fast Packet Protocol

examples/vt_version_3_object_pool/main.cpp, isobus/include/isobus/isobus/can_warning_logger.hpp, isobus/src/can_warning_logger.cpp, sphinx/source/Tutorials.rst, sphinx/source/Tutorials/Debug Logging.rst
* Fixes a segfault when using a custom logger
* Adds tutorial and example documentation for implementing a custom logger
Closes #70
=> [Core/Meta]: Custom logger fix and documentation

examples/vt_version_3_object_pool/main.cpp, isobus/include/isobus/isobus/isobus_virtual_terminal_client.hpp, isobus/src/can_extended_transport_protocol.cpp, isobus/src/can_parameter_group_number_request_protocol.cpp, isobus/src/can_transport_protocol.cpp, isobus/src/isobus_virtual_terminal_client.cpp
Adds support for the 7 VT activation messages in the form of callbacks which were still missing.
Closes #81
=> [VT] Add remaining activation message callbacks

isobus/src/can_address_claim_state_machine.cpp, isobus/src/isobus_virtual_terminal_client.cpp
Fixed a couple small issues that were generating warnings on some compilers
=> Fix a couple small warnings, one for Windows, and one sketchy comparision

README.md
Thank you to my sponsors, your support really motivates me to keep working on this project and funds additional hardware and software to drive up quality and bring forward new features.
$25+ Sponsors get featured in the readme for the duration of their sponsorship.
=> [Meta]: Update readme, add special thanks section

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Added some issue templates to help standardize incoming requests for the project.
=> [#101]: Add issue templates

isobus/src/isobus_virtual_terminal_client.cpp
Previously the data callback method of uploading an object pool was not working. Now we call the user supplied callback inside the internal callback wrapper.
Tested using a modified version of the example code.
Simply add a callback for data chunks: (though, maybe use one that is less sketchy)
```
bool testDataChunkCallback(std::uint32_t callbackIndex,
std::uint32_t bytesOffset,
std::uint32_t numberOfBytesNeeded,
std::uint8_t *chunkBuffer,
void *parentPointer)
{
memcpy(chunkBuffer, &testPool.data()[bytesOffset], numberOfBytesNeeded);
return true;
}
```
And register for data callbacks rather than calling `set_object_pool`
```
TestVirtualTerminalClient->register_object_pool_data_chunk_callback(0, isobus::VirtualTerminalClient::VTVersion::Version3, testPool.size(), testDataChunkCallback); …
```
=> [#125]: Add processing of user supplied data chunk callbacks for VT uploads

isobus/src/can_extended_transport_protocol.cpp
We had a condition where we might close and abort a Tx session, but then try to update the closed session. Now we'll not do that. If the session is closed, we will not further update the session in that state.
=> [ETP]: Fix a crash in ETP when aborting while in a TxDataSession state

isobus/include/isobus/isobus/isobus_virtual_terminal_client.hpp, isobus/src/isobus_virtual_terminal_client.cpp
Also moved VirtualTerminalClient::StateMachineState to private since no other classes access it
=> [VT]: Add public check for if client is connected

.github/workflows/sonar.yml, sonar-project.properties
Added github action for scanning the repo with sonar cloud
=> [Meta]: Add sonar cloud scanner

.github/workflows/build.yml, CMakeLists.txt, isobus/CMakeLists.txt, isobus/include/isobus/isobus/can_general_parameter_group_numbers.hpp, isobus/include/isobus/isobus/isobus_language_command_interface.hpp, isobus/src/isobus_language_command_interface.cpp, test/language_command_interface_tests.cpp
This is intended to be a component of VT and TC client interfaces.
I'll add it to VT once #65 merges so that I can more easily add unit tests.
=> [VT/TC]: Add language command interface

hardware_integration/src/can_hardware_interface.cpp
This fixes a crash that might manifest if your CAN hardware is invalid and you call `Start` on the hardware interface.
=> [Core]: Fix a crash that can occur if a hardware channel is nullptr

doxyfile
Updated doxyfile to remove obsolete variables.
=> [Meta]: Update doxyfile to 1.9.1

isobus/src/can_parameter_group_number_request_protocol.cpp, isobus/src/isobus_diagnostic_protocol.cpp, isobus/src/nmea2000_fast_packet_protocol.cpp
Just two simple changes:
1. Fixed the shift for the upper byte of a PGN.
2. Switched to `auto &` instead of `auto` in a few `for` loops to avoid copies.
=> Minor fixes

examples/virtual_terminal/version3_object_pool/main.cpp, sphinx/source/Tutorials/Virtual Terminal Basics.rst
Updates to VT tutorial:
- Use atomic running boolean flag instead of _exit()
- Add context pointer to CAN update callback
- Use available can drivers for driver initiation
- Add more context to smaller snippets (where which line should be located)
- Switch to the new dispatcher system for key event
Also contains some fixes for Sonar warnings in the VT example main file
Closes #217
=> [Meta]: Update VT tutorial to match latest example

CMakeLists.txt, CONTRIBUTING.md, examples/README.md, examples/diagnostic_protocol/main.cpp, examples/pgn_requests/README.md, library.json, sphinx/source/API Documentation.rst, sphinx/source/Concepts.rst, sphinx/source/FAQ.rst, sphinx/source/Installation.rst, sphinx/source/Tutorials/Adding a Destination.rst, sphinx/source/Tutorials/Debug Logging.rst, sphinx/source/Tutorials/Receiving Messages.rst, sphinx/source/Tutorials/The ISOBUS Hello World.rst, sphinx/source/Tutorials/Transport Layer.rst, sphinx/source/Tutorials/Virtual Terminal Basics.rst, sphinx/source/conf.py, sphinx/source/index.rst
* Changed repo name in a few places.
* Removed the legacy can stack "glue" since the hardware layer calls the needed functions directly now.
=> [Meta]: Update tutorials to reflect the changes in #219

CMakeLists.txt, isobus/CMakeLists.txt, isobus/include/isobus/isobus/can_general_parameter_group_numbers.hpp, isobus/include/isobus/isobus/isobus_maintain_power_interface.hpp, isobus/src/isobus_maintain_power_interface.cpp, test/maintain_power_tests.cpp
* Adds a maintain power interface (for PGN 65095).
- Allows sending and receiving the maintain power message. Parses out the SPNs within the message for your easy use.
- Re-implements a tiny subset of the `SpeedMessagesInterface` from #266 to allow parsing the key switch state if the user is not using the `SpeedMessagesInterface` to manage it themselves
- Allows users to get a callback when receiving the maintain power message (useful if you are programming a tractor ECU)
- Allows users to get a callback when the key transitions from the "not off" to "off" state
The message this interface manages can be sent by any CF connected to the implement bus requesting that the Tractor ECU not switch off the power for 2 seconds after it has received the wheel-based speed and distance message …
=> [#253]: Add maintain power interface

isobus/src/nmea2000_fast_packet_protocol.cpp
* Fixed sending or receiving one extra packet when the total data count in a FP session was exactly on a frame boundary.
* Fixed crash with some FP sessions where setting multipacket payloads would overrun the bounds of the message data vector. 
* Clarified a log message.
(cherry picked from commit 8fd14ac6253d02eb96f9385157943aff848be36e)
=> [FP]: Fixed fast packet session packet count issues

.github/workflows/build.yml
Added compilation checks for Windows and Mac platforms.
Part of #320
=> Add Windows and Mac OS builds

.github/workflows/pio.yml, examples/virtual_terminal/esp32_platformio_object_pool/platformio.ini, isobus/src/nmea2000_message_interface.cpp, library.json
=> [CI] Add PlatformIO pipeline

isobus/include/isobus/isobus/isobus_virtual_terminal_objects.hpp
=> [Meta]: Doxygen fixes

.readthedocs.yaml, sphinx/requirements.txt, sphinx/source/conf.py
- Added a file which should fix our failing sphinx doc builds.
- Forced version of sphinx and our theme to fixed at a known version
A working build based on this branch:
https://readthedocs.org/projects/isobus-plus-plus/builds/22726322/
Closes #369
=> [Meta]: Add .readthedocs.yaml

isobus/include/isobus/isobus/isobus_virtual_terminal_objects.hpp, isobus/src/isobus_virtual_terminal_objects.cpp, test/vt_object_tests.cpp
- Added VT objects for Aux Input type 1 and 2.
- Added VT objects for Aux Functions type 1 and 2.
- Added Auxiliary Control Designator Type 2 Object
=> [VT]: Add VT objects for Aux inputs and Aux functions

sphinx/source/Tutorials/Virtual Terminal Basics.rst
Insert Changes from examples/virtual_terminal/version3_object_pool/main.cpp
Else, the Example is not able to build under Windows
=> Update Virtual Terminal Basics.rst

hardware_integration/include/isobus/hardware_integration/toucan_vscp_canal.hpp, hardware_integration/src/toucan_vscp_canal.cpp
This will make this plugin easier to configure after construction such as in AgISOVirtualTerminal.
=> [HW]: Allow reconfiguring the TouCAN plugin at runtime

.github/ISSUE_TEMPLATE/bug_report.md, CMakeLists.txt, CONTRIBUTING.md, README.md, examples/README.md, hardware_integration/lib/README.md, sphinx/README.md
Used [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) for formatting markdownfiles
=> Improve documentation on examples and apply formatting

.github/workflows/build.yml, .github/workflows/linting.yml, .github/workflows/pio.yml
This should at least speed up the actions building for PlatformIO a bit
=> Enable caching for Python PIP

isobus/include/isobus/isobus/isobus_virtual_terminal_client.hpp, isobus/src/isobus_virtual_terminal_client.cpp
A bit less to maintain I guess
=> [VT]: Refactor similar 'send_can_message' function calls to smaller alternative

.github/pull_request_template.md
=> Github PR template

isobus/include/isobus/isobus/isobus_virtual_terminal_client_update_helper.hpp, isobus/src/isobus_virtual_terminal_client_state_tracker.cpp, test/helpers/control_function_helpers.cpp, test/helpers/control_function_helpers.hpp, test/helpers/messaging_helpers.cpp, test/helpers/messaging_helpers.hpp
Removed random extra semicolons which showed up as warnings with -Wpedantic
Tested that unit tests compile, which should be enough for this one.
=> [Misc]: Fix -Wpedantic issues

sphinx/source/Tutorials/Adding a Destination.rst, sphinx/source/Tutorials/ESP32 PlatformIO.rst, sphinx/source/Tutorials/Receiving Messages.rst, sphinx/source/Tutorials/The ISOBUS Hello World.rst, sphinx/source/Tutorials/Virtual Terminal Basics.rst, utility/include/isobus/utility/thread_synchronization.hpp
- Fixed some discrepancies between the basic tutorials and our latest API. 
- Removed calls to exit from the tutorials, opting instead for our normal "while running" loops. 
- Removed one annoying semicolon.
Fixes #442 
I compiled each of the tutorials' final states, and they compiled properly now. None of the changes were really "functional" changes.
=> [Docs]: Update the basic tutorials

examples/task_controller_server/main.cpp, sphinx/source/Tutorials/Receiving Messages.rst
Added missing CF re-factorization because #463 was merged without updating the base branch and hence the missing updates were missed by the CI/CD pipeline.
=> [TC-server] fix missing CF refactorization to TC server

README.md
Thanks for sponsoring continued development in these projects!
=> Update Sponsors in README

isobus/src/isobus_data_dictionary.cpp
When tried to cross compile the stack with Microchip XC32 it reported a warning about a possible fallthrough.
Added a break and the code compiled.
=> Fixing possible fall through

examples/nmea2000/nmea2000_generator/main.cpp, examples/nmea2000/nmea2000_parser/main.cpp
Added missing chrono includes.
Added two missing includes.
Built and ran unit tests, verified all examples compiled locally.
=> Fixed two examples which weren't compiling after the latest MSVC update.

isobus/src/can_internal_control_function.cpp, isobus/src/can_network_manager.cpp
This changes fixes an issue where a J1939 style claim (without a request for the address claim PGN) that evicts an internal control function would not trigger an appropriate address claim response from an internal control function. Also, this fixes a todo regarding contention for an address when an ICF NAME is configured not to support self configurable addressing. Now those situations should be handled properly.
Tested with a custom set of applications crafted to simulate these conditions, essentially modified versions of our examples.
=> Fix legacy J1939 address claims could be ignored, contend for non arbitratable NAME preferred addresses

isobus/include/isobus/isobus/isobus_virtual_terminal_server.hpp, isobus/src/isobus_virtual_terminal_objects.cpp, isobus/src/isobus_virtual_terminal_server.cpp
Added event dispatcher from the stack to signal softkeymask changes
Necessary for Open-Agriculture/AgIsoVirtualTerminal#71
Built AgIsoVT where this event handler is used.
=> isobus vt: Add event dispatcher for signaling softkey mask change

isobus/src/can_network_manager.cpp
If a J1939 address claim evicts an internal control function, this will perform the name comparison to determine if it should send another claim for its old address or not. This will make it so we exactly match the J1939 address claiming procedure when dealing with non-ISO 11783 devices.
Fixes #564
Tested by manually sending address claims while one of our example applications was running.
Also, I used the debugger to confirm that the control functions' internal address variable and the address table both got properly updated in these cases.
=> Handle J1939 address evictions better

isobus/include/isobus/isobus/isobus_virtual_terminal_server.hpp
Built AgIsoVT with screen capture support
=> Add enum for screen capture response error codes

isobus/include/isobus/isobus/isobus_virtual_terminal_working_set_base.hpp, isobus/src/isobus_virtual_terminal_working_set_base.cpp
Moved macro reference parsing to a separate function, and added where it was marked as TODO
Fixes martonmiklos/AgIsoVirtualTerminal#23
Loaded Vaderstad Tempo implement and the warning message is gone
=> iop parsing: Implement macro reference parsing

isobus/include/isobus/isobus/isobus_virtual_terminal_server.hpp, isobus/src/isobus_virtual_terminal_server.cpp
Added support for change line attribute command
Fixes # (issue)
In the settings menu of a John Deere M732  this command was utilized, but not implemented.
Built AgIsoVT with this change, actual testing was not yet done.
=> Add support for change line attribute command

isobus/include/isobus/isobus/isobus_virtual_terminal_server.hpp, isobus/src/isobus_virtual_terminal_server.cpp
Add support for sending response to the GetWindowMaskDataMessage in the VT server implementation
Built AgIsoVT with this and tried to run NX9 VT6 test implement
=> Add get window mask response

isobus/include/isobus/isobus/isobus_virtual_terminal_objects.hpp
=> Fix OutputString inverted attribute comment
